# Jersey colour classification in football video

In [1]:
import torch
import pandas as pd
import numpy as np

from dataset import load_manifest, get_loader
from models import load_model
from extract_embeddings import get_embeddings, extract_all_models
from classification_clustering import compare_models
from visualization import interactive_embedding_view, plot_confusion_matrix

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torchreid\reid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
from pathlib import Path

manifest_path = Path("dataset_v1/manifest_with_splits.csv")

if manifest_path.exists():
    df = load_manifest(manifest_path)
else:
    print("dataset_v1/manifest_with_splits.csv not found, fallback to ../dataset/manifests/*.csv")
    manifests_dir = Path("../dataset/manifests")
    parts = []
    for split_name in ["train", "val", "test"]:
        p = manifests_dir / f"{split_name}.csv"
        if not p.exists():
            continue
        part = pd.read_csv(p)
        if "split" not in part.columns:
            part["split"] = split_name
        parts.append(part)

    if not parts:
        raise FileNotFoundError(
            "No manifests found. Expected dataset_v1/manifest_with_splits.csv or ../dataset/manifests/{train,val,test}.csv"
        )

    df = pd.concat(parts, ignore_index=True)

    # Convert detection-level manifest to the format used by this notebook.
    df["crop_path"] = df["image_path"]
    df["game"] = df["source_folder"]
    df["label"] = np.where(
        df["role_name"].astype(str).str.strip().str.lower() == "goalkeeper",
        "goalkeeper",
        np.where(df["left2right"].astype(int) == 1, "team_left", "team_right"),
    )

print("dataset size:", len(df))
df.head()

dataset size: 64291

,crop_path,label,game,src_image,x1,y1,x2,y2,frame_idx,player_id,role_name,left2right,split
0,dataset_v1/crops/game_10_H1__frame_001877__i0_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1399,522,1475,667,1877,101,Left Central Back,1,train
1,dataset_v1/crops/game_10_H1__frame_001877__i1_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1524,290,1591,408,1877,103,Right Central Back,1,train
2,dataset_v1/crops/game_10_H1__frame_001877__i2_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1091,874,1171,1067,1877,104,Left Back,1,train
3,dataset_v1/crops/game_10_H1__frame_001877__i3_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,77,549,126,704,1877,105,Left Midfielder,1,train
4,dataset_v1/crops/game_10_H1__frame_001877__i4_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,185,169,223,269,1877,106,Right Winger,1,train

In [4]:
df["game"].unique()[:20]

<StringArray>
['game_10_H1', 'game_10_H2', 'game_11_H1', 'game_11_H2', 'game_12_H1',
 'game_12_H2', 'game_13_H1', 'game_13_H2', 'game_14_H1', 'game_14_H2',
 'game_15_H1', 'game_15_H2', 'game_16_H1', 'game_16_H2', 'game_17_H1',
 'game_17_H2', 'game_19_H1', 'game_19_H2',  'game_1_H1',  'game_1_H2']
Length: 20, dtype: str

## game_12

In [5]:
base_game = "game_12"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 716 H2: 695 Total: 1411

In [6]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_right    680
team_left     636
goalkeeper     95
Name: count, dtype: int64

In [8]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["dino", 'osnet']
)

========================================
  модель: dino
========================================

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

loading cached embeddings
  готово: shape=(1452, 768)

========================================
  модель: osnet
========================================
Successfully loaded imagenet pretrained weights from "C:\Users\KM/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
loading cached embeddings
  готово: shape=(1452, 512)

### Metrics

In [8]:
df_report = compare_models(embeddings)

df_classification = df_report[[
    "lr_accuracy",
    "lr_macro_f1",
    "mlp_accuracy",
    "mlp_macro_f1",
    "macro_f1_delta_mlp_minus_lr",
    "best_lr",
    "best_mlp",
]].copy()

df_clustering = df_report[["cluster_acc", "cluster_macro_f1", "sil_euclidean", "sil_cosine"]].copy()
df_clustering = df_clustering.rename(columns={
    "cluster_acc": "kmeans_acc",
    "cluster_macro_f1": "kmeans_macro_f1",
    "sil_euclidean": "kmeans_sil_euclidean",
    "sil_cosine": "kmeans_sil_cosine",
})

print("Classification comparison: Logistic Regression vs 2-layer MLP")
display(df_classification)

print("Clustering metrics (k-means)")
display(df_clustering)

evaluating dino...
evaluating osnet...
Classification comparison: Logistic Regression vs 2-layer MLP

,lr_accuracy,lr_macro_f1,mlp_accuracy,mlp_macro_f1,macro_f1_delta_mlp_minus_lr,best_lr,best_mlp
model,,,,,,,
dino,0.9717,0.9551,0.9717,0.9551,0.0000,+,+
osnet,0.9576,0.9035,0.9682,0.9526,0.0491,,

Clustering metrics (k-means)

       kmeans_acc  kmeans_macro_f1  kmeans_sil_euclidean  kmeans_sil_cosine
model
dino       0.7371           0.6198                0.0964             0.1731
osnet      0.7512           0.6209                0.0934             0.1710

### Visualization

In [9]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1411 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_12_H1', '692', '101',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_12_H1', '692', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABHACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDHopSKB15rwbHCJgEVBcgMjIXYICN7K2NoJ9e1dJ4S0GTWr8GVVTT4pQlxKX27zjcUTuzYHbpmum8UX3hvxP4JuNB8P6Y2n2Kx+c/kJztD7S2FBMjDqcsMdOa6KeGlNaHXRiup535cUV9JBbLII44lLb51lwT9DRWn4N0yw0vwndw61bz3zyzPm9RghglUERBFx8ykYJBIx70VMqE4uwqlNcxQPIoFFL+OOazOS7Gwa1qFg1xbWOoJBYS7RfIw3DAOc44I9yCM96ZpQltV8nT7iRULSRF2O1iC3msR7EYB+oq/Y6D9vju9QAWH7GiFn8ovv3k4Vhnn7pP4U29ktNdktLVoJJrwwOhgPz+Z3MjNjCZO0cDpgdq9jBp2O6LXKMuJ45742mmS3NxbQQCa52RkKGJxu2nkKMAZPcUVJG8vh+aSPTym6W3WC7WJ9kcy4OVJGS2D646UVhXl77M5SVyrQOvFMZtuKhubyG0j8y6kWNG+6cjPtXDGLZzrcvW2rf2cmsXs17cQ2GnabJJNAh/dzTupSJSB1PJwK8ii+IHiN7+NvtNuskaDkWqbgMAAdOwArtfGGqzqLWHSSsZdFMsZQP58mCFds9wG6DioU8LaHYWNnFdaeDOxDXUkbHLNzx7DNd2Gr+y3O1JWsaHge9udV0GS+v5mnnNw65PAQdeBiirfhy0h0/Szbwhgjyl8E5x6UVy1anNK5x1GoysdX8M9MtdY8Z2i6ioaxsw15OhGd4jzhf8AvrB+gNcR4w0a98U+LNW1zWNYuG+1XTNDFEABHFnhR6flXQ6LrNzo9xNc2mzzJbdoGLLng5z/ADrNSYCMDJ496yVTlWhKZDp2k2VhHFsRpJYvuSSsScdh6cewrN8Y6wmmQWoIk3TseUbaQB1xxW8jh1+8PxrmfHPnR3WitavCt3558pnAYBTkHg9aUJuT1LjN3Og0iRZtJs5o+FaEcE5I9qKfGixQRQpyI1C5xjJ/p9KKT3M56u5W3npmiiisGHQdGWVsgV6T8Kb/AMASeHp/C/iFJ/7Q1qeTe5tw2Bj5NrgEqRgkehFFFaU9wicb4l0yLRNU+xQaxHrFu6mSG5WJo3C7iArqwHzcdRxRRRWjY2f/2Q=='],
                                   ['team_left', 'game_12_H1', '692', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA+ABoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDyRFZVZlZcgdzx1r2p/B+oeFPD2lW9vqA1aTUZfNuYYImHk5QNwc4bAOCexFeS+EbGS+8S6fbC1luka4RpY4zgmNTub+VfQ1n4jZntNZMXmL9maKCJ/uKGDupOO+I1xXVJRqaX1NYe6eR/FD4d6x4Rt7fV5ZFuNMv2HlSkYaKRl3CNx646HviuF2S/8869j8T61f638MNZn1KeGJYyYLW0aQHMqyrkrnk8MSBzgV5Qd+fu1SpcqtcU3dnfeBIn8K6ReeL54/3swNhpu4HaGbl5D9BxXbeGbK4ttA07T7pYXuCsc7sxG3Z5Um1sZ6/NjB6H8q8+1PVZ59GW3uWU2tlHujTAAGPWqum/F6SS+ijvdBjkn3IkZgm2b8gKq4x14Bx61x4GsptuRManOzsPFcUMXgp9MO6PzNXMsYyGwnlKMjj7uQfxHtXBHTLT3/M13XxOkt47nS9Pt5WkMNqfNJUptk3EshUgEEZxXHZHrXLiMVJVHymVSpZl97CHX7ebTFjs7ATIf3uwnGPqa4ux8A3DapcOmtFvIH7p4YyDvHPGDwR1/CukmDSRtH5kiBhglG2nH1riPI8TeHNSuJLR5ry3uVKkxs+V92A74B9q46NVpWRNCpGKdz0Y65ruoz3Oo6xcw3N3PID5hhHKgY6HucA0z+0rv1i/78p/hWN4au7u88OWV3dW80Yk3IjvGVWTacEqT1weM1frKabZhOV3cbgg9as6bpt/r12NC0y1a4vbuOTyo14LFUJ6ngfU8VAa6bwB4ul8FzXl/Z6TaXWoXKeVHczucwJ12qAO55NTSXvGavc5Cwtr/SdFstC1RbiG605Wja3mHzQuTmRfbnFP8w1b1q8n1bWb3WLzYbq8lMkxQYUt3wO1VvLFazsmO5//2Q=='],
                                   ['team_left', 'game_12_H1', '692', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABSACQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDl1G7oRWl4aFraa5Y6xdtcQzWbk2pC/JuPBfng7cjsa6j4bx2eiz2Ou6nYQXI1OeSysopIvMKsgyX54BJ+UfnVrx/qdx4qtdNvtK+0RTQC38m0mUb5ftnmK0YA4G3y92e2a8SlgK8o86WhGFSUrs5rx1qCanqsVw1zczSwxhJJJUUZJHLcDGG6/hXPsBnK5x713Pwz/svQ/D7T61Gs9rfabFqEmIPOQBrk26RFD1IJJyD39qh8f6RoC6nfP4SQfY7A7bmGGTegxw0iZ52qw2sDyDU1MLV3aNMTBTd0cXRS4J7A0VzWZwcjOj8VtrunXWi6MLlYRHawXsVzHw4j2n90QOnXk9TW1ol6SdCMgHkQXFrIJWj6iGKU7hyeN8i8e3visvVvEbalo+n6UtvGn2W2WEy4y8hAwB7Dk/pVeG/lgltYYlbzLd5TPOTgqy6fIVRR7k5J5wfWvfy+pKpouh3RlBLQu3VzdSeD9P8ADv2eMQmPT9OmnQfN50UkkkiDPIUHbz3NcxZ6bcW1xc30NzshutzXYA5DscvjnoxPI9q1/CkVxf6lYwR5WNf7KkYMSQCbNyST/eLHk1Y8U2ltpq2mn2d/FexvbLNcMoAKTE/PEw9R/KnmEpQjZMuMko3ZiOiqRskGMZ5FFR9aK8DU43UJNLEbalbGZgkQfLsegAUn+YAq/NaNbrNtRYSlvcTSkMchhphLfl5nauZ8UIz+F9TCOqOsG4AtjdyOB715VpWv60l+0Vrq17Gk6sjhLkkMjLtZcEHqvFe5lEeSLbLowb1PoFdDvolWCKe6jLXttG4wRI/2fTVkJyM4AJArJdiSxb7zNuYnBJJ6kmszwjd6preh6rqmoatqIuYryKS0kVx5ZlaPZKrAeqKF6dhVx2ZnLZJ+prHNKyk0kKrJpWJ16UVFvorxzmuR3tpBe2slrcRh45FKsMdq5r4VaF4Tmn8RtdeZMkMYgt3aTYVbk5GPfjnrXUxklgAcc9TXit9Je6f4r1O00svbSksZAjdQD1/riu7CylytJnVQnZWPWtAsU0+2ube3uZJ7YzkoGPCnvir5wDxXOfDSea58LJNPK8rGV/mY5zznNdE55rkrtuepFXVicUUc0VlcxsJ171xHi2CS68apJpNn5t79kIlIxhsADp9K7Vj8vfp2qfUrjTbfV7e803SG8pIwjrNIQzHA5yK3o1OS56OBpUJXlVlZIwPAiS2vhW2SaPy3JJ2/lWqZMtxSSTyTs37qOGPdlUToB2Hv9aYE96ib5nc5sRJc9o7EwkGKKiwaKzsYEp6CmP8AdoooREvgCiiiqQ1sFFFFMD//2Q=='],
                                   ...,
                                   ['team_left', 'game_12_H2', '148775', '111',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgADoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDiviHY+ZpEF5oclzeOXCRo+A+D947R+HNeWL4lCXeJrWR0z5ckTsVyTxzjrXq8kzrGCZdkajD4Ucr3FWE8AW+hz6t44XytOvNBlt5fst8vmwzTTLuWEqCG80qQcAgAEZ5rzsDP2jtY0pSUqV0cv8MNbgt7Y2N3oNrNJGWMZnL568dDz9DXexeKZ4Bi10nSbduzJAdw/E16P4k13xX4Y8J6bqfj2S0udN16RBLFHGsDacW7eWACyBcHOcqTzXmHjnSZ9A8QyWb2skVvN+9tJcZjnjIzuR8kMPoTSxcakG3HY5Z0upak8Y6/Jn/So4xn/lnHg/zNU7jxBrE7AyalOcduBj8hWOJDQXNeU69V/aOTqX5dQu5hia8uXH+1KT+mah3L/eNVQ1OyfasnUk+oGr4QfTk8TabLqwDWUdwrzKWCq4B4ViexOBXRfELVUk+H2uz38z2DT+N5TcXMC+YBII1Nt5gP3UxgBl6YBGa4uNFbIZA4IwVzjIPFaOnW+it4d1TQde1iK2sb2DYJJIvMmn8r5oMogLlkbKbiACjdeK9fLp04Nykzsws21ynd/D3X/wDhLtNubzxXrsF7qsAHh/TtPlI2XSTJlxKoOSzkY80fdwODzXC+FdWksPB76Dd6XCNJiupVj02dmdrdwxBKO3KEHHTg46VzOv6deeEPiroV9owb+zdSu7aaAIrKqMkqhlBbrjnrXpvxr0G30fx/qSW8ly32iRrq4Eq5RJZDkKj55+Xkgjj6V24qrGpQcou6NqjsmefAcdPzp+Cak8o/WnCI5r5xo81u7IguO1O4qVozio9h96XKIkVlU4AxVqCRIALhnKNnI5x071BbQiZtoXceprK8U31ta28s1xIsdtGuyFScNNIf/ZRzk1tSpuckkd+C9z3mYnxM1iTVPENpq+mT3Uun20gYojlFiuoyCxxyFzgEN0r3J7C+8WzWulx6hcKt9btqunQarcJPeSTlAJh5yOySQhRwV5GfuivMvCmt3Gn61/b/AIQaNrkWiCztjGstvOsabntrjoQ7AMV9xjmvS9Mkg1DR9N1bRtKWXwpqzpJqGn6WGX+yJmyU1C0LY+zsjffUEKcH8fo6dOnRp+znsdFZe01RwcyLE7Rk/MpKkehHBqNZAexrY8Z6tpGsa7JJp13a6jd2yCHU9Ss1Mdvf3IPMka9uANxHBJOOKwlK9OlfOV7KbUdjyZrldiUyA8U3cKbhfWlwvoPzrO5Nyxpl99jEvyIRIu07lJI+mK4f40aNr8jRXwtvtFiIcqsGSYs4++B6+1dskUaSqXOFU5JqTXdX8uyN5EysWwqljt57da6qFTkdz1cJGMqbTZ88+Hb3XIdYtYNCu72G9knTyVtpSjNKflXGCPm5x+New+C9D8QadoX9i+KNMSCK9uJY7Y3JV3ikxmSKRc5QkfOuevUU+TQ9NmWZrzT7aeedSHkMYyM9cen1qLW/EEllffZL2GfS7Ce0ihlvLdTc/aHgx9nKRnAidcbSQTkE12V8RHE03Fbip1Ep8pD4O0y90S71Tw7cRGX7Pi5iliQlWhPAY+g6dehroo4ufmq74D1HUdT1W41y+0r7MF0ua1ggRxumMi4dpM87e4Ud6z494VV5+UAH8K8mpUk5e/v1MMVR5ZXRMyRj7rHHvUXHrSFmJpMVNzhehIsrBsk5rzb4p293pt9HcWzEWd37s2x+4GSQPwr0JHO4ZGayfH2nLrPh14YxtmiPmIfcdq2wdTlqJPqbQm0yD4fanPqfh5PPcyPbuYt5P3hjINdC8InhaOQHa1cT8KL24/s+exnwqwu2wAAck8/Wu2E7g/KRRifcraBdp3K+nXeoeHrpZBO00EfKljnaPfvWdqfj/SL/AMRpbi2jigWMK88Xy737tithisy4cZzwcDrXnfj7wuYJ/wC1NJiwmcvCnJU+o9qdDkqSakdEsQ5qzPSVUMgZASGGRyDkU3y5P7tcn8P/ABC2o2n2GYO13EcAYOWHpj1rr91wODDMD7xms6tP2crHM4SeyKYkRRliB9a3PDOhNrsmXil+w8iSVHC/kTWLbXjWEy3MUcLuh+UTRCRc+6mrmt+OvFOq24s5JrOC2GAFtYBFx6cVzTlNfAdeDjhr81Z/I6nS/A3w90xJryzN602Pmea9BjB6noAM9+K5PUIoYrphbtuiJO3nPesiCRAn+p2kdy24n3qYSO5yT+lW6k5O8tysZXozsqUbWLBYLSkRyLgqHB/h9artz1NNGVJwTU+8tTgjud58KtM0jwxq0uv2emWx1CWPh5TnZ9B0H1612kvjrUjIxP2LJJz/AKOteaW9zZWukK41EG4fGV3cj1GKy2v/AJj+6Q89d55rmqVsRUlq9j6ulWw2HpRW7e5//9k='],
                                   ['team_left', 'game_12_H2', '148775', '112',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABGACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDlo0y1WW+SNiATgZx61HCDmtXQrKfUdYt7K2lggkfLNLO4SOJB1dieABkfnXgQTex59KKlJJmKbPxLZXtq+o22ntZzjIe1uknKZHG7YeOnerrJj/61dToVld+INWvtIF35S2+Umu/JUxjGcEgHJTP8QyKyvEegatoM0I1FYWjnz5M0L745Meh/EfnV8klujqxNFKzRkgUU/OeRRSscZNp8Fo9vPJdXqwNGo8qPClpmP8IBYfnU9pepo3lXFxK0LXF5BEFViHeAEs/GPmDEquBnpk1nOqMm1lBHcEVBaW7RTq8tw8yxAiAMBmPOM89+g+n41dGoodDek438zvbmS2P2G1s7WY3ct7JbzSQSFHzKh2BHA+Ulhw3v7VhaH4g1S1tQNc06fUtI1JVmSO42ThnAIy5QR7XB4LqFJx8was221S8gmngG6SOYRzRNuwI5I2Vo2A9cgg+oNamvNfnWrbTbWEpocN7qMk6xJlYmLo6YP0Y8V6mIrNUlKOh204Kb1IfEGm2+n3KGyvFuLWYbox/Gn+y350VRmmeaQsx+g9KK8lq7ucVZRU3ykGKO3JoJ4roPBVnYNdnVtXET2dnIuIJORO+Cdp9sdazgtRUaTnKyKFppN4dEPiB7V5dPh3tN5DK9wsCYEsqx5yVGcYzuPYHnHTWWo3VtPb3OsajHDpt3K0s1pdlFFjHKAsCt3EmMNt6YI44rg7iPXIbm5sPA1vFqFlaytcWdtJIsaTSSN96SNztnaPopOSAQMGvOYvCXibxR4vurvWLu2t9QlmLXLyJj5iccKgwBXoKtpZ7HpRp8qseoSr5croT912UHHUA9fxopLuwGmPFYm8a8eGNVknMHlb274G5vzorjm1fQ8yompETfWo53ufs0kNvN5ZfqGGVYe4o3Gm/Xmsk7Ewm4O6ON1a38Uadr02qW0dvcAxLD/orYAUD0bH4V6D8HLTUvGPi+1sIoWtZAS90WQbUQD3qgMZyeld54F8RJ4X0C6vbZEinuSY1ZP9ZIRnj9a19omrGyxEr3OZ8V6por6/c2MF15ktrcSQ52Y3bSOaK4TxLoVzJdNq9mzfalkMjIRnfk5OaKSjfUxnNydzpW4pvNFFYkCMSBTXb5RySFyQD2z1oopAb/AIP0C98RXDLazQRpFgSCUkZDZ6YB9KKKK6Y7Af/Z'],
                                   ['team_left', 'game_12_H2', '148775', '113',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDk9med1Mupo7aCS4lbCRqXY+gA5qTIxUN5bQ3llPaTfcmjaM+2R1r5amk5K55yscda+O7efVY4liX7K7YDE/MM967DcwbrmvGbHw7qMXi9dEARrhLhY4yWChyT8vJ6Zr3658K+JtPyl34e1VQi/wCsW0eSM4HOHUFT+dd+Jw7unTVzapSbSsZgaky/9w0KysuVIIziml2z1rz23HRmdrEmeM1paRp9lLp91reuX66foljk3EwYebI3aOJf4nOce1ZLMwU8dBWT8TNQuYNK0zwu2nxz2t7b/aElXIa3uT9w56DIyMdwa9DLqUZTc5K6Q6UVKWp3Y8HaT4/1Sy1XxRrmleE/DcelC40lYmVnng3EESTsADMrD5lwxAPA71T8V+H9Gh8KRXHwk03xpqFzZXSvdahaG4ktHjH31DggN0BDKvHPPatH4ITfC3W9K0bwU/gK+8TaiY5X1d5w2+wI+88YLYwT/cIb2rW+HPi7Xbr4mv4QtdfmsPB3hPzhFcRxCIzxgDYlx2JXkZwCcZPNe5Gpzao72raHLXmqDxZ4TtvGQtGgvoyLfWVwVBJJEFzg9VkAKMw43rzgmsYnHXrWTqnxXvYNTI09TbR/bru3N9BOCJbGSTcYGiZShG7LhuoycVrj51V1YMrAEH1B6GvFzKCU04o46q1JBz9TXESfEO4vNVvNL1Kw+2H7QqxSQ8SMsfCIVAwceo5rtlI45qvBY6fbzy3MFlbRTvkvIsYVifr1Fc+HrqknfqTSdpHV/s7S6bJ4v8QeSqaHq9xpqzxOZRlUHErITwWHUqfrXX6JY/8ACIrqMXgXw/pviXS9UCvPdazrkCYuP+WjnBLMjDkr27da5XVmtL1JPt1tYXIgtZpY41ALIwg/vja3A7etXbKPRGaaK40W2mDXelq5Nsm8q8YGQQOWr6fBYaPslY63N7HnHx6fW/FNpeXOpWnhsTaeqC3m0H5reSNc7lDcbyB3x2ql4BuZL3wlYSMzMyR+WSM/wnFel6nYxv4WlhJYxWszoE3DYUVyv3Oxx3B9jXm/g3SZtO0l4YLxJIWuJHi8sZ2qTwD715eZQUXymMouRrkgdKqXWoT2TM9jBPc3oikeCKE/OzKhbIHfGM4HPFWCOOtcP8Szcxx2U9lIRLA5kPkv+9iYYw/HKj0NePQgqk0jOj8RX074x61FGI9Z0611ghGjMsjvDKQylSCyHB4PUjNdbqfxbj0eO3W48DgTTwWssbDVpMDyf9WfuZ3evPNZvhvSr6/t11TxIY7m/m5Blt4wyr2LELlmPqas+LtG0u9shc6rBezi3GQbSZI3A7/eBBrveJgpciTt5NnT9Yu7DbD4paz4o1JtMSxsNK0+bzJJIrRWLOWOSGdiSRnnHFdHZmOCHy3tYJDnO7cy/wAjiuX8HN4OikZND8P3hnZCPtOo3wldP91URVB9zmui2leBXHiKjlPZkV5uMtxm4nArzGGdte8fQ+cp2m424U4O1M/4V6VdypDbyzqW/dxs/p0BrifhVC7rf3bwxlAVjWRogXLHk4Y8jjsPWt8O1ClKRzw3O681sjii4Ant5I5FDK6kEUoAAzSkjHrXCnqLrc5DwzLp+n65LZrHdNOGI3MqqoH05J/Su0eRc8cCuHuNP1b/AIS4X9tZyNbFsNKoBH5V2WHPOD+VdWKSik0VUfMdv8OPAGpavrGnX2s6NOnhslZrqe5jKwzRHgID/FuOBx0GSa5vxto+g+G/FeqaR4btzb6dDOCibyw3lAXxnoMnAHYAVjt4q8ZwRx241Z5tPjTYlo8jFFGMD5c9qprNdzgPcvJJIfvO7ZY/U0e2gqPs0tSW49Cz53YmkMw9ag8s4pCSnbIrjSsQjntWiK+I7a4Z1GG4Bb+hrsopv3Y+lehfCbxl4YtNJbR9d+z22c5nNssjD36ZrF16y8B/2pM2neMruaBm3ZXSzgE9QORxXoVacZ0o2Zof/9k=']],
                                  shape=(636, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '72b40284-5b4f-4f9f-a6a2-88926d82a996',
              'x': {'bdata': ('nyStQDtLl0Ae2aJAsnW7QE+l5UCGoM' ... '+oQGHkxkBI/IxAfQbTQGNixUDX7PFA'),
                    'dtype': 'f4'},
              'y': {'bdata': ('LZTgwADL7MC6kgDB7e3wwJYD8cCZsd' ... 'y2wBqQ38C8nPzAjTvTwAeJzMBEqt3A'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_12_H1', '692', '200',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABRAC0DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDmrmUwWk0wRnMcbOFHU4Gay5fB3jKfw0PFTeJLCNZYvtNvpsU7ebInpjGM9Rj2rY5OFHJbgADrWnqG/wAMLHa6hYw2t9dW/mRMY1EqjPCkjoeM49DXk4XDVKvwq5OGnR1UzItPtDWNvJcxmOZ4w0insaecg9a9RsvC3giXT4LjUbfXy0sYleRb1Rt+UE8BQcVwU+l2kklzLot8b+1iJbbICJ0XPcdG+oroxGR4mEHUtoedOvDnaRlnrRTnCg/KQRTa8Vpp2Ze5seCNZttD11dSu7WK48uNlg8xQQkp4V+eMjqKvanfQ318ZbnyZ71m80JJEXAYnqGf7x9844rA0uKO9aWwmgWQTRkJkZwwHHFY1xBqun3/APZbpcPOxOyKQNwM4G0EdP0r9A4bxFKFDlklc8zF06ilzRZ3EviAw2Nyt1m4W5AVCH249ee4xxj0rD8KKum+J7e6eZbezluhJcoqBw8bDG0DHXA57VktAY51trlx5u4eZKJd+xRz5ax9u/zE9+lbRtDcWIv7fPmkKdgU4JUH/wDXXt5lKUqLcehhhrSqpSK9/DHb6neQQ58hLh/KJHVM5HHb0/Coa3vGGmNZ3MVz5kLJOo5R8ktjnPvjFYVflFZv2jbPdnDkfKMgmeCZZomKOhyCDgg1uW2twXEhutatRezxj5JimSoyMA+oz61z9dH8Ob2ws/FVvDq8FtNpd6Da3gnjDKqNjDc+hrowtVqolfQpSVjl5rW0S/ke4laIyv5ixJIBu7gYB6V3vgzwprWrWNzd2IjW1ijwAUbYWI+6uFx6c9ea9qHhXwcmnE2GlWsIkPy3Frp7PHkcAkhMf/qq/wDD+aU6ReTt9ma5RmQ2kPyxxuvRQMcZ47Z5r7d45ujyIxjhFzc58tXonTUJoroFbiJzFIh/gIPT/PrTOtdZ8YoLZPHd1d2gRY9QhjuiquGCSEFXXI44Irkh9a+GxsOStI0knfUrA85pVcK+cgcdxn9Krh89KaznNc0ZOLJTPV/Cnxf17S9H0zQzHamGA7JrgIWlK5wMDpkD656V2mn3nibQtUGoXWlyarb60zvCFnEUkTgDlgF4B4wOe9fPVvNJGyyx53Idy49RXq1h4z1zX7eSR9RtrQ2ypcQuoCmNxxsx3zzXvYDEuTakzrhWVuWw749nUbz+xddv9Lt9N83zLdIVnEkrDAOX7DHt0ry/djggmug+Ic2v/wBsLZa/M8k8f+kQOfuujD7y/wBa5rfnrxXm5lrVbRzVd7lPcVOBQCaHGDSVxdDIA7L0p0dy0TK/PykEAHuO9NIyKi8sk4zThNwldFqVj0M+K9F8TeC7bw5qljdXPiaIyDSZ7dctGuMvvJwBFjqOee1cOrZRT14rU8Ma9NoVpcwxWlvJJPuAlZfnQFcHB9MZ4rGRTGgRdxC55/HNXVre03OysqXsotPUV+tNFFFZo88d2oX7wooqGUhx6mkP3jRRQWf/2Q=='],
                                   ['team_right', 'game_12_H1', '692', '201',

## game_50

In [4]:
base_game = "game_40"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 740 H2: 712 Total: 1452

In [5]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_left     705
team_right    694
goalkeeper     53
Name: count, dtype: int64

In [6]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["osnet", "dino", "dinov2_large", "fastreid"],
)

========================================
  модель: osnet
========================================
Successfully loaded imagenet pretrained weights from "C:\Users\KM/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
loading cached embeddings
  готово: shape=(1452, 512)

========================================
  модель: dino
========================================

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

loading cached embeddings
  готово: shape=(1452, 768)

========================================
  модель: dinov2_large
========================================

Using cache found in C:\Users\KM/.cache\torch\hub\facebookresearch_dinov2_main
C:\Users\KM/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
C:\Users\KM/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
C:\Users\KM/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")

loading cached embeddings
  готово: shape=(1452, 1024)

========================================
  модель: fastreid
========================================
loading cached embeddings
  готово: shape=(1452, 2048)

### Metrics

In [8]:
df_report = compare_models(embeddings)

df_classification = df_report[[
    "lr_accuracy",
    "lr_macro_f1",
    "mlp_accuracy",
    "mlp_macro_f1",
    "macro_f1_delta_mlp_minus_lr",
    "best_lr",
    "best_mlp",
]].copy()

df_clustering = df_report[["cluster_acc", "cluster_macro_f1", "sil_euclidean", "sil_cosine"]].copy()
df_clustering = df_clustering.rename(columns={
    "cluster_acc": "kmeans_acc",
    "cluster_macro_f1": "kmeans_macro_f1",
    "sil_euclidean": "kmeans_sil_euclidean",
    "sil_cosine": "kmeans_sil_cosine",
})

print("Classification comparison: Logistic Regression vs 2-layer MLP")
display(df_classification)

print("Clustering metrics (k-means)")
display(df_clustering)

evaluating osnet...
evaluating dino...
evaluating dinov2_large...
evaluating fastreid...
Classification comparison: Logistic Regression vs 2-layer MLP

,lr_accuracy,lr_macro_f1,mlp_accuracy,mlp_macro_f1,macro_f1_delta_mlp_minus_lr,best_lr,best_mlp
model,,,,,,,
dino,0.9725,0.9320,0.9759,0.9524,0.0205,,+
fastreid,0.9622,0.8819,0.9588,0.8795,-0.0024,,
dinov2_large,0.9656,0.8292,0.9691,0.8315,0.0024,,
osnet,0.9691,0.9477,0.9553,0.8221,-0.1256,+,

Clustering metrics (k-means)

,kmeans_acc,kmeans_macro_f1,kmeans_sil_euclidean,kmeans_sil_cosine
model,,,,
dino,0.7431,0.6061,0.1023,0.1866
fastreid,0.6612,0.5268,0.0775,0.1413
dinov2_large,0.8719,0.6582,0.0667,0.1215
osnet,0.7479,0.5677,0.0886,0.1638

### Visualization

In [14]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '93fb2a16-2410-4bb2-98f2-e9a8651b9c2c',
              'x': {'bdata': ('aAK+vzDfCMAulF+/ijZov+BL+78n91' ... 'iYv5a4pr8Y2AfAMAoIwBA4A8DtSYS/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('Q2qmQNBbrED5d5ZAPzXmQC80qUBuH8' ... 'nuQOqi20CTFgxB9ksCQQvXs0B7AvNA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

## Metric Learning - Improve Embeddings

In [11]:
from metric_learning import MetricLearningTrainer, EmbeddingHead
from sklearn.model_selection import train_test_split
results_list = []
losses_to_test = ["triplet", "contrastive", "arcface"]

for model_key, (X_orig, y_orig) in embeddings.items():
    
    orig_rep = compare_models({model_key: (X_orig, y_orig)}).loc[model_key]

    for l_type in losses_to_test:
        print(f"--- Training {l_type.upper()} head for {model_key} ---")
        
        head = EmbeddingHead(in_dim=X_orig.shape[1], out_dim=128, hidden_dim=256).to(device)
        trainer = MetricLearningTrainer(model=head, device=device, learning_rate=1e-3, loss_type=l_type)
        
        trainer.train(embeddings=X_orig, labels=y_orig, epochs=15, batch_size=128, val_split=0.9)
        
        X_ref = trainer.transform(X_orig)
        ref_rep = compare_models({f"tmp": (X_ref, y_orig)}).loc["tmp"]
        
        results_list.append({
            "Base Model": model_key,
            "Loss Type": l_type,
            "orig_kmeans_acc": orig_rep['cluster_acc'],
            "refined_kmeans_acc": ref_rep['cluster_acc'],
            "orig_kmeans_f1": orig_rep['cluster_macro_f1'],
            "refined_kmeans_f1": ref_rep['cluster_macro_f1'],
            "orig_sil_eucl": orig_rep['sil_euclidean'],
            "refined_sil_eucl": ref_rep['sil_euclidean'],
            "orig_sil_cos": orig_rep['sil_cosine'],
            "refined_sil_cos": ref_rep['sil_cosine'],
        })

full_comparison_df = pd.DataFrame(results_list)

display(full_comparison_df)

evaluating osnet...
--- Training TRIPLET head for osnet ---
Training triplet loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 2.7049, Val Loss: 2.7181
Epoch 2/15 - Loss: 1.6797, Val Loss: 3.1718
Epoch 3/15 - Loss: 0.7264, Val Loss: 3.7518
Epoch 4/15 - Loss: 0.1192, Val Loss: 4.3632
Epoch 5/15 - Loss: 0.0041, Val Loss: 5.0353
Epoch 6/15 - Loss: 0.0000, Val Loss: 5.7072
Epoch 7/15 - Loss: 0.0000, Val Loss: 6.3539
Epoch 8/15 - Loss: 0.0000, Val Loss: 6.9178
Epoch 9/15 - Loss: 0.0000, Val Loss: 7.4183
Epoch 10/15 - Loss: 0.0000, Val Loss: 7.8537
Epoch 11/15 - Loss: 0.0000, Val Loss: 8.2478
Epoch 12/15 - Loss: 0.0000, Val Loss: 8.5473
Epoch 13/15 - Loss: 0.0000, Val Loss: 8.8229
Epoch 14/15 - Loss: 0.0000, Val Loss: 9.0472
Epoch 15/15 - Loss: 0.0000, Val Loss: 9.2814
evaluating tmp...
--- Training CONTRASTIVE head for osnet ---
Training contrastive loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 0.2811, Val Loss: 0.1019
Epoch 2/15 - Loss: 0.1189, Val Loss: 0.0824
Epoch 3/15 - Loss: 0.0641, Val Loss: 0.0681
Epoch 4/15 - Loss: 0.0453, Val Loss: 0.0558
Epoch 5/15 - Loss: 0.0330, Val Loss: 0.0461
Epoch 6/15 - Loss: 0.0242, Val Loss: 0.0393
Epoch 7/15 - Loss: 0.0206, Val Loss: 0.0349
Epoch 8/15 - Loss: 0.0150, Val Loss: 0.0322
Epoch 9/15 - Loss: 0.0119, Val Loss: 0.0302
Epoch 10/15 - Loss: 0.0091, Val Loss: 0.0287
Epoch 11/15 - Loss: 0.0077, Val Loss: 0.0276
Epoch 12/15 - Loss: 0.0072, Val Loss: 0.0268
Epoch 13/15 - Loss: 0.0065, Val Loss: 0.0261
Epoch 14/15 - Loss: 0.0051, Val Loss: 0.0255
Epoch 15/15 - Loss: 0.0047, Val Loss: 0.0251
evaluating tmp...
--- Training ARCFACE head for osnet ---
Training arcface loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 3.6403, Val Loss: 0.8134
Epoch 2/15 - Loss: 0.3434, Val Loss: 0.7862
Epoch 3/15 - Loss: 0.0508, Val Loss: 0.7793
Epoch 4/15 - Loss: 0.0455, Val Loss: 0.6788
Epoch 5/15 - Loss: 0.0012, Val Loss: 0.6388
Epoch 6/15 - Loss: 0.0203, Val Loss: 0.6122
Epoch 7/15 - Loss: 0.0158, Val Loss: 0.5750
Epoch 8/15 - Loss: 0.0019, Val Loss: 0.5547
Epoch 9/15 - Loss: 0.0002, Val Loss: 0.5632
Epoch 10/15 - Loss: 0.0008, Val Loss: 0.5400
Epoch 11/15 - Loss: 0.1091, Val Loss: 0.5280
Epoch 12/15 - Loss: 0.0000, Val Loss: 0.4586
Epoch 13/15 - Loss: 0.0000, Val Loss: 0.4308
Epoch 14/15 - Loss: 0.0000, Val Loss: 0.4392
Epoch 15/15 - Loss: 0.0002, Val Loss: 0.4455
evaluating tmp...
evaluating dino...
--- Training TRIPLET head for dino ---
Training triplet loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 3.2795, Val Loss: 4.0989
Epoch 2/15 - Loss: 1.8438, Val Loss: 5.1710
Epoch 3/15 - Loss: 1.3131, Val Loss: 6.7384
Epoch 4/15 - Loss: 0.2160, Val Loss: 7.9546
Epoch 5/15 - Loss: 0.0641, Val Loss: 9.0615
Epoch 6/15 - Loss: 0.0203, Val Loss: 9.7259
Epoch 7/15 - Loss: 0.0120, Val Loss: 10.2213
Epoch 8/15 - Loss: 0.0049, Val Loss: 10.6521
Epoch 9/15 - Loss: 0.0000, Val Loss: 11.3904
Epoch 10/15 - Loss: 0.0000, Val Loss: 11.5521
Epoch 11/15 - Loss: 0.0000, Val Loss: 11.8951
Epoch 12/15 - Loss: 0.0000, Val Loss: 11.9188
Epoch 13/15 - Loss: 0.0000, Val Loss: 12.0909
Epoch 14/15 - Loss: 0.0000, Val Loss: 12.0256
Epoch 15/15 - Loss: 0.0000, Val Loss: 12.0711
evaluating tmp...
--- Training CONTRASTIVE head for dino ---
Training contrastive loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 0.2569, Val Loss: 0.0672
Epoch 2/15 - Loss: 0.0905, Val Loss: 0.0483
Epoch 3/15 - Loss: 0.0457, Val Loss: 0.0401
Epoch 4/15 - Loss: 0.0302, Val Loss: 0.0343
Epoch 5/15 - Loss: 0.0227, Val Loss: 0.0295
Epoch 6/15 - Loss: 0.0169, Val Loss: 0.0259
Epoch 7/15 - Loss: 0.0125, Val Loss: 0.0230
Epoch 8/15 - Loss: 0.0100, Val Loss: 0.0213
Epoch 9/15 - Loss: 0.0085, Val Loss: 0.0207
Epoch 10/15 - Loss: 0.0062, Val Loss: 0.0198
Epoch 11/15 - Loss: 0.0055, Val Loss: 0.0192
Epoch 12/15 - Loss: 0.0047, Val Loss: 0.0187
Epoch 13/15 - Loss: 0.0041, Val Loss: 0.0183
Epoch 14/15 - Loss: 0.0037, Val Loss: 0.0180
Epoch 15/15 - Loss: 0.0033, Val Loss: 0.0178
evaluating tmp...
--- Training ARCFACE head for dino ---
Training arcface loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 3.4952, Val Loss: 0.6358
Epoch 2/15 - Loss: 0.3232, Val Loss: 0.6921
Epoch 3/15 - Loss: 0.0786, Val Loss: 0.6072
Epoch 4/15 - Loss: 0.0417, Val Loss: 0.5637
Epoch 5/15 - Loss: 0.0001, Val Loss: 0.5116
Epoch 6/15 - Loss: 0.0000, Val Loss: 0.4549
Epoch 7/15 - Loss: 0.0121, Val Loss: 0.4537
Epoch 8/15 - Loss: 0.0002, Val Loss: 0.4063
Epoch 9/15 - Loss: 0.0011, Val Loss: 0.3921
Epoch 10/15 - Loss: 0.0031, Val Loss: 0.3656
Epoch 11/15 - Loss: 0.0562, Val Loss: 0.3364
Epoch 12/15 - Loss: 0.0001, Val Loss: 0.3197
Epoch 13/15 - Loss: 0.0000, Val Loss: 0.3161
Epoch 14/15 - Loss: 0.0000, Val Loss: 0.3158
Epoch 15/15 - Loss: 0.0000, Val Loss: 0.3166
evaluating tmp...
evaluating dinov2_large...
--- Training TRIPLET head for dinov2_large ---
Training triplet loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 5.2118, Val Loss: 4.3491
Epoch 2/15 - Loss: 4.6897, Val Loss: 5.2491
Epoch 3/15 - Loss: 2.6025, Val Loss: 5.9778
Epoch 4/15 - Loss: 1.7299, Val Loss: 6.0999
Epoch 5/15 - Loss: 1.5514, Val Loss: 6.3163
Epoch 6/15 - Loss: 1.4326, Val Loss: 6.8419
Epoch 7/15 - Loss: 1.2022, Val Loss: 7.4501
Epoch 8/15 - Loss: 1.0755, Val Loss: 7.8932
Epoch 9/15 - Loss: 0.9970, Val Loss: 8.1485
Epoch 10/15 - Loss: 0.9639, Val Loss: 8.4213
Epoch 11/15 - Loss: 0.1341, Val Loss: 8.4950
Epoch 12/15 - Loss: 0.9565, Val Loss: 8.5153
Epoch 13/15 - Loss: 0.0570, Val Loss: 8.4356
Epoch 14/15 - Loss: 0.9575, Val Loss: 8.1624
Epoch 15/15 - Loss: 0.9612, Val Loss: 7.8581
evaluating tmp...
--- Training CONTRASTIVE head for dinov2_large ---
Training contrastive loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 0.2927, Val Loss: 0.0974
Epoch 2/15 - Loss: 0.0994, Val Loss: 0.0838
Epoch 3/15 - Loss: 0.0530, Val Loss: 0.0771
Epoch 4/15 - Loss: 0.0376, Val Loss: 0.0689
Epoch 5/15 - Loss: 0.0285, Val Loss: 0.0591
Epoch 6/15 - Loss: 0.0232, Val Loss: 0.0518
Epoch 7/15 - Loss: 0.0170, Val Loss: 0.0487
Epoch 8/15 - Loss: 0.0132, Val Loss: 0.0465
Epoch 9/15 - Loss: 0.0108, Val Loss: 0.0470
Epoch 10/15 - Loss: 0.0108, Val Loss: 0.0463
Epoch 11/15 - Loss: 0.0091, Val Loss: 0.0394
Epoch 12/15 - Loss: 0.0067, Val Loss: 0.0346
Epoch 13/15 - Loss: 0.0058, Val Loss: 0.0316
Epoch 14/15 - Loss: 0.0052, Val Loss: 0.0300
Epoch 15/15 - Loss: 0.0050, Val Loss: 0.0287
evaluating tmp...
--- Training ARCFACE head for dinov2_large ---
Training arcface loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 3.2532, Val Loss: 0.9875
Epoch 2/15 - Loss: 0.7803, Val Loss: 0.8089
Epoch 3/15 - Loss: 0.0509, Val Loss: 0.6065
Epoch 4/15 - Loss: 0.0611, Val Loss: 0.5171
Epoch 5/15 - Loss: 0.0777, Val Loss: 0.4916
Epoch 6/15 - Loss: 0.1560, Val Loss: 0.4557
Epoch 7/15 - Loss: 0.0745, Val Loss: 0.4198
Epoch 8/15 - Loss: 0.0430, Val Loss: 0.4018
Epoch 9/15 - Loss: 0.0001, Val Loss: 0.4040
Epoch 10/15 - Loss: 0.0062, Val Loss: 0.4032
Epoch 11/15 - Loss: 0.0239, Val Loss: 0.4190
Epoch 12/15 - Loss: 0.0474, Val Loss: 0.4644
Epoch 13/15 - Loss: 0.0012, Val Loss: 0.5792
Epoch 14/15 - Loss: 0.0004, Val Loss: 0.8228
Epoch 15/15 - Loss: 0.0275, Val Loss: 0.7245
evaluating tmp...
evaluating fastreid...
--- Training TRIPLET head for fastreid ---
Training triplet loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 3.1415, Val Loss: 1.2919
Epoch 2/15 - Loss: 2.9778, Val Loss: 1.5005
Epoch 3/15 - Loss: 1.2650, Val Loss: 1.7013
Epoch 4/15 - Loss: 0.1144, Val Loss: 1.9086
Epoch 5/15 - Loss: 0.0166, Val Loss: 2.1580
Epoch 6/15 - Loss: 0.0039, Val Loss: 2.4327
Epoch 7/15 - Loss: 0.0000, Val Loss: 2.7582
Epoch 8/15 - Loss: 0.0000, Val Loss: 3.1295
Epoch 9/15 - Loss: 0.0000, Val Loss: 3.5399
Epoch 10/15 - Loss: 0.0000, Val Loss: 3.9706
Epoch 11/15 - Loss: 0.0000, Val Loss: 4.4066
Epoch 12/15 - Loss: 0.0003, Val Loss: 4.8401
Epoch 13/15 - Loss: 0.0000, Val Loss: 5.3067
Epoch 14/15 - Loss: 0.0000, Val Loss: 5.7435
Epoch 15/15 - Loss: 0.0000, Val Loss: 6.1683
evaluating tmp...
--- Training CONTRASTIVE head for fastreid ---
Training contrastive loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 0.2599, Val Loss: 0.0688
Epoch 2/15 - Loss: 0.0753, Val Loss: 0.0511
Epoch 3/15 - Loss: 0.0391, Val Loss: 0.0422
Epoch 4/15 - Loss: 0.0257, Val Loss: 0.0375
Epoch 5/15 - Loss: 0.0190, Val Loss: 0.0347
Epoch 6/15 - Loss: 0.0151, Val Loss: 0.0321
Epoch 7/15 - Loss: 0.0115, Val Loss: 0.0297
Epoch 8/15 - Loss: 0.0106, Val Loss: 0.0271
Epoch 9/15 - Loss: 0.0068, Val Loss: 0.0256
Epoch 10/15 - Loss: 0.0055, Val Loss: 0.0245
Epoch 11/15 - Loss: 0.0048, Val Loss: 0.0239
Epoch 12/15 - Loss: 0.0051, Val Loss: 0.0231
Epoch 13/15 - Loss: 0.0037, Val Loss: 0.0229
Epoch 14/15 - Loss: 0.0033, Val Loss: 0.0225
Epoch 15/15 - Loss: 0.0033, Val Loss: 0.0225
evaluating tmp...
--- Training ARCFACE head for fastreid ---
Training arcface loss for 15 epochs
  Train: 146 samples
  Val: 1306 samples
Epoch 1/15 - Loss: 4.7935, Val Loss: 0.7634
Epoch 2/15 - Loss: 0.0914, Val Loss: 1.0804
Epoch 3/15 - Loss: 0.0422, Val Loss: 1.2490
Epoch 4/15 - Loss: 0.0006, Val Loss: 1.3639
Epoch 5/15 - Loss: 0.0035, Val Loss: 1.4556
Epoch 6/15 - Loss: 0.1925, Val Loss: 1.2202
Epoch 7/15 - Loss: 0.0073, Val Loss: 0.8564
Epoch 8/15 - Loss: 0.0117, Val Loss: 0.6538
Epoch 9/15 - Loss: 0.0278, Val Loss: 0.4960
Epoch 10/15 - Loss: 0.0002, Val Loss: 0.4386
Epoch 11/15 - Loss: 0.0000, Val Loss: 0.3920
Epoch 12/15 - Loss: 0.0000, Val Loss: 0.3610
Epoch 13/15 - Loss: 0.0000, Val Loss: 0.3468
Epoch 14/15 - Loss: 0.0014, Val Loss: 0.3598
Epoch 15/15 - Loss: 0.0006, Val Loss: 0.3604
evaluating tmp...

,Base Model,Loss Type,orig_kmeans_acc,refined_kmeans_acc,orig_kmeans_f1,refined_kmeans_f1,orig_sil_eucl,refined_sil_eucl,orig_sil_cos,refined_sil_cos
0,osnet,triplet,0.7479,0.9690,0.5677,0.9133,0.0886,0.5348,0.1638,0.7605
1,osnet,contrastive,0.7479,0.9745,0.5677,0.9464,0.0886,0.7368,0.1638,0.9101
2,osnet,arcface,0.7479,0.9318,0.5677,0.8282,0.0886,0.3491,0.1638,0.5569
3,dino,triplet,0.7431,0.9697,0.6061,0.9156,0.1023,0.5937,0.1866,0.8125
4,dino,contrastive,0.7431,0.9821,0.6061,0.9723,0.1023,0.8116,0.1866,0.9437
5,dino,arcface,0.7431,0.9766,0.6061,0.9574,0.1023,0.5178,0.1866,0.7460
6,dinov2_large,triplet,0.8719,0.9690,0.6582,0.9122,0.0667,0.4946,0.1215,0.7238
7,dinov2_large,contrastive,0.8719,0.9545,0.6582,0.8638,0.0667,0.6835,0.1215,0.8615
8,dinov2_large,arcface,0.8719,0.8430,0.6582,0.7117,0.0667,0.3673,0.1215,0.5584
9,fastreid,triplet,0.6612,0.8347,0.5268,0.6421,0.0775,0.4530,0.1413,0.6171
10,fastreid,contrastive,0.6612,0.9642,0.5268,0.8569,0.0775,0.8108,0.1413,0.9447
11,fastreid,arcface,0.6612,0.9463,0.5268,0.8486,0.0775,0.4953,0.1413,0.7153

### Visualization: Embedding Space Comparison

In [17]:
model_name = "osnet"
X_orig, y_orig = embeddings[model_name]

refined_embeddings = {
    "osnet_original": (X_orig, y_orig)
}

for l_type in losses_to_test:
    print(f"\n--- Training {l_type.upper()} for {model_name} ---")
    

    head = EmbeddingHead(in_dim=X_orig.shape[1], out_dim=128, hidden_dim=256).to(device)
    

    trainer = MetricLearningTrainer(model=head, device=device, learning_rate=1e-3, loss_type=l_type)
    
    trainer.train(embeddings=X_orig, labels=y_orig, epochs=15, batch_size=128, val_split=0.8)
    

    X_refined = trainer.transform(X_orig)
    refined_embeddings[f"{model_name}_{l_type}"] = (X_refined, y_orig)

--- Training TRIPLET for osnet ---
Training triplet loss for 15 epochs
  Train: 291 samples
  Val: 1161 samples
Epoch 1/15 - Loss: 2.7718, Val Loss: 2.4396
Epoch 2/15 - Loss: 1.8799, Val Loss: 2.9682
Epoch 3/15 - Loss: 1.2567, Val Loss: 3.6163
Epoch 4/15 - Loss: 0.5646, Val Loss: 4.3717
Epoch 5/15 - Loss: 0.1058, Val Loss: 4.9664
Epoch 6/15 - Loss: 0.0302, Val Loss: 5.5023
Epoch 7/15 - Loss: 0.0116, Val Loss: 6.1678
Epoch 8/15 - Loss: 0.0042, Val Loss: 6.8023
Epoch 9/15 - Loss: 0.0000, Val Loss: 7.3027
Epoch 10/15 - Loss: 0.0003, Val Loss: 7.8051
Epoch 11/15 - Loss: 0.0000, Val Loss: 8.1405
Epoch 12/15 - Loss: 0.0003, Val Loss: 8.4062
Epoch 13/15 - Loss: 0.0015, Val Loss: 8.6007
Epoch 14/15 - Loss: 0.0000, Val Loss: 8.7655
Epoch 15/15 - Loss: 0.0000, Val Loss: 8.8246

--- Training CONTRASTIVE for osnet ---
Training contrastive loss for 15 epochs
  Train: 291 samples
  Val: 1161 samples
Epoch 1/15 - Loss: 0.2307, Val Loss: 0.0777
Epoch 2/15 - Loss: 0.0721, Val Loss: 0.0529
Epoch 3/15 - Loss: 0.0378, Val Loss: 0.0410
Epoch 4/15 - Loss: 0.0252, Val Loss: 0.0335
Epoch 5/15 - Loss: 0.0177, Val Loss: 0.0289
Epoch 6/15 - Loss: 0.0133, Val Loss: 0.0262
Epoch 7/15 - Loss: 0.0112, Val Loss: 0.0244
Epoch 8/15 - Loss: 0.0088, Val Loss: 0.0231
Epoch 9/15 - Loss: 0.0082, Val Loss: 0.0221
Epoch 10/15 - Loss: 0.0070, Val Loss: 0.0213
Epoch 11/15 - Loss: 0.0051, Val Loss: 0.0207
Epoch 12/15 - Loss: 0.0050, Val Loss: 0.0203
Epoch 13/15 - Loss: 0.0040, Val Loss: 0.0203
Epoch 14/15 - Loss: 0.0038, Val Loss: 0.0205
Epoch 15/15 - Loss: 0.0030, Val Loss: 0.0205

--- Training ARCFACE for osnet ---
Training arcface loss for 15 epochs
  Train: 291 samples
  Val: 1161 samples
Epoch 1/15 - Loss: 2.0407, Val Loss: 2.2543
Epoch 2/15 - Loss: 0.1624, Val Loss: 1.4708
Epoch 3/15 - Loss: 0.0658, Val Loss: 0.9355
Epoch 4/15 - Loss: 0.0153, Val Loss: 0.6368
Epoch 5/15 - Loss: 0.0001, Val Loss: 0.4288
Epoch 6/15 - Loss: 0.0005, Val Loss: 0.3629
Epoch 7/15 - Loss: 0.0007, Val Loss: 0.3337
Epoch 8/15 - Loss: 0.0005, Val Loss: 0.3238
Epoch 9/15 - Loss: 0.0009, Val Loss: 0.3267
Epoch 10/15 - Loss: 0.0001, Val Loss: 0.3352
Epoch 11/15 - Loss: 0.0002, Val Loss: 0.3408
Epoch 12/15 - Loss: 0.0002, Val Loss: 0.3397
Epoch 13/15 - Loss: 0.0001, Val Loss: 0.3346
Epoch 14/15 - Loss: 0.0142, Val Loss: 0.3187
Epoch 15/15 - Loss: 0.0000, Val Loss: 0.2981

In [19]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_original"
X, y = refined_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '0da40891-706a-400c-874d-662fd7492f13',
              'x': {'bdata': ('aAK+vzDfCMAulF+/ijZov+BL+78n91' ... 'iYv5a4pr8Y2AfAMAoIwBA4A8DtSYS/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('Q2qmQNBbrED5d5ZAPzXmQC80qUBuH8' ... 'nuQOqi20CTFgxB9ksCQQvXs0B7AvNA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

In [20]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_triplet"
X, y = refined_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': 'ec6e6835-0922-41b7-b119-3c6061dc966c',
              'x': {'bdata': ('MyoLwXe7DMEBGA3BFPr+wBICDsGU2Q' ... '4Dweas/MC62bnAyv7fwJXPBcHUwPfA'),
                    'dtype': 'f4'},
              'y': {'bdata': ('HdgjQTDSN0ENByNBTiFAQd/9I0HrnF' ... 'dAQYmZRkFIgkZBT6s0QTapJkF97zlB'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

In [21]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_contrastive"
X, y = refined_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '50293726-4d14-4e42-828f-7764def24ccd',
              'x': {'bdata': ('iw7LPfJsnD8uID4+sviuP1P41z7aqu' ... 'zTvWUjjD9VCkY+sxA0v9LH5j5lP8i9'),
                    'dtype': 'f4'},
              'y': {'bdata': ('klYjQV5YN0GyXh5BKL01QaMOIUE+XT' ... '41QaSnMkEHglFBV/FEQV9sK0G/lEtB'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

In [22]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_arcface"
X, y = refined_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': 'c389cde3-b835-4cba-acb4-cfca18a49b91',
              'x': {'bdata': ('/SmmQT8ErEE7qKNBVi6yQbzMp0G797' ... 'CsQQzwrUG7KL5BJp+uQVg1qEHEAatB'),
                    'dtype': 'f4'},
              'y': {'bdata': ('8C1QQNwuJUAt1kpAnfN5QDDsR0BJ6y' ... '+KQGkXdEDfYqtAf6SYQG9mXkCKX4pA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

## Unsupervised Metric Learning - SimCLR

In [7]:
from metric_learning import SimCLRTrainer, EmbeddingHead
results_list = []

for model_key, (X_orig, y_orig) in embeddings.items():
    
    orig_rep = compare_models({model_key: (X_orig, y_orig)}).loc[model_key]

    print(f"--- Training SimCLR head for {model_key} ---")
    
    head = EmbeddingHead(in_dim=X_orig.shape[1], out_dim=128, hidden_dim=256).to(device)
    trainer = SimCLRTrainer(model=head, device=device, learning_rate=1e-3, temperature=1.0)
    
    trainer.train(embeddings=X_orig, epochs=15, batch_size=128, val_split=0.1)
    
    X_ref = trainer.transform(X_orig)
    ref_rep = compare_models({f"tmp": (X_ref, y_orig)}).loc["tmp"]
    
    results_list.append({
        "Base Model": model_key,
        "Loss Type": "simclr",
        "orig_kmeans_acc": orig_rep['cluster_acc'],
        "refined_kmeans_acc": ref_rep['cluster_acc'],
        "orig_kmeans_f1": orig_rep['cluster_macro_f1'],
        "refined_kmeans_f1": ref_rep['cluster_macro_f1'],
        "orig_sil_eucl": orig_rep['sil_euclidean'],
        "refined_sil_eucl": ref_rep['sil_euclidean'],
        "orig_sil_cos": orig_rep['sil_cosine'],
        "refined_sil_cos": ref_rep['sil_cosine'],
    })

simclr_comparison_df = pd.DataFrame(results_list)

display(simclr_comparison_df)

evaluating osnet...
--- Training SimCLR head for osnet ---
Training SimCLR: 1307 train, 145 val
Epoch 1/15 - Loss: 4.7404, Val Loss: 4.9665
Epoch 2/15 - Loss: 4.6036, Val Loss: 4.8495
Epoch 3/15 - Loss: 4.5720, Val Loss: 4.7948
Epoch 4/15 - Loss: 4.5536, Val Loss: 4.7772
Epoch 5/15 - Loss: 4.5423, Val Loss: 4.7704
Epoch 6/15 - Loss: 4.5350, Val Loss: 4.7663
Epoch 7/15 - Loss: 4.5309, Val Loss: 4.7631
Epoch 8/15 - Loss: 4.5264, Val Loss: 4.7574
Epoch 9/15 - Loss: 4.5236, Val Loss: 4.7571
Epoch 10/15 - Loss: 4.5206, Val Loss: 4.7553
Epoch 11/15 - Loss: 4.5184, Val Loss: 4.7532
Epoch 12/15 - Loss: 4.5173, Val Loss: 4.7507
Epoch 13/15 - Loss: 4.5153, Val Loss: 4.7493
Epoch 14/15 - Loss: 4.5145, Val Loss: 4.7455
Epoch 15/15 - Loss: 4.5128, Val Loss: 4.7481
evaluating tmp...
evaluating dino...
--- Training SimCLR head for dino ---
Training SimCLR: 1307 train, 145 val
Epoch 1/15 - Loss: 4.7035, Val Loss: 4.8357
Epoch 2/15 - Loss: 4.5733, Val Loss: 4.7856
Epoch 3/15 - Loss: 4.5452, Val Loss: 4.7634
Epoch 4/15 - Loss: 4.5312, Val Loss: 4.7558
Epoch 5/15 - Loss: 4.5224, Val Loss: 4.7516
Epoch 6/15 - Loss: 4.5158, Val Loss: 4.7459
Epoch 7/15 - Loss: 4.5119, Val Loss: 4.7409
Epoch 8/15 - Loss: 4.5086, Val Loss: 4.7388
Epoch 9/15 - Loss: 4.5065, Val Loss: 4.7355
Epoch 10/15 - Loss: 4.5045, Val Loss: 4.7315
Epoch 11/15 - Loss: 4.5022, Val Loss: 4.7297
Epoch 12/15 - Loss: 4.5008, Val Loss: 4.7295
Epoch 13/15 - Loss: 4.4993, Val Loss: 4.7283
Epoch 14/15 - Loss: 4.4982, Val Loss: 4.7255
Epoch 15/15 - Loss: 4.4973, Val Loss: 4.7270
evaluating tmp...
evaluating dinov2_large...
--- Training SimCLR head for dinov2_large ---
Training SimCLR: 1307 train, 145 val
Epoch 1/15 - Loss: 4.7208, Val Loss: 4.8513
Epoch 2/15 - Loss: 4.5658, Val Loss: 4.7872
Epoch 3/15 - Loss: 4.5413, Val Loss: 4.7687
Epoch 4/15 - Loss: 4.5318, Val Loss: 4.7588
Epoch 5/15 - Loss: 4.5238, Val Loss: 4.7498
Epoch 6/15 - Loss: 4.5194, Val Loss: 4.7455
Epoch 7/15 - Loss: 4.5152, Val Loss: 4.7405
Epoch 8/15 - Loss: 4.5122, Val Loss: 4.7386
Epoch 9/15 - Loss: 4.5095, Val Loss: 4.7334
Epoch 10/15 - Loss: 4.5067, Val Loss: 4.7334
Epoch 11/15 - Loss: 4.5052, Val Loss: 4.7328
Epoch 12/15 - Loss: 4.5031, Val Loss: 4.7312
Epoch 13/15 - Loss: 4.5019, Val Loss: 4.7288
Epoch 14/15 - Loss: 4.5004, Val Loss: 4.7287
Epoch 15/15 - Loss: 4.4995, Val Loss: 4.7262
evaluating tmp...
evaluating fastreid...
--- Training SimCLR head for fastreid ---
Training SimCLR: 1307 train, 145 val
Epoch 1/15 - Loss: 4.6733, Val Loss: 4.8916
Epoch 2/15 - Loss: 4.5541, Val Loss: 4.7735
Epoch 3/15 - Loss: 4.5301, Val Loss: 4.7493
Epoch 4/15 - Loss: 4.5172, Val Loss: 4.7432
Epoch 5/15 - Loss: 4.5117, Val Loss: 4.7371
Epoch 6/15 - Loss: 4.5086, Val Loss: 4.7337
Epoch 7/15 - Loss: 4.5053, Val Loss: 4.7310
Epoch 8/15 - Loss: 4.5032, Val Loss: 4.7315
Epoch 9/15 - Loss: 4.5015, Val Loss: 4.7286
Epoch 10/15 - Loss: 4.4997, Val Loss: 4.7268
Epoch 11/15 - Loss: 4.4982, Val Loss: 4.7273
Epoch 12/15 - Loss: 4.4965, Val Loss: 4.7270
Epoch 13/15 - Loss: 4.4956, Val Loss: 4.7249
Epoch 14/15 - Loss: 4.4950, Val Loss: 4.7250
Epoch 15/15 - Loss: 4.4937, Val Loss: 4.7209
evaluating tmp...

,Base Model,Loss Type,orig_kmeans_acc,refined_kmeans_acc,orig_kmeans_f1,refined_kmeans_f1,orig_sil_eucl,refined_sil_eucl,orig_sil_cos,refined_sil_cos
0,osnet,simclr,0.7479,0.7314,0.5677,0.6057,0.0886,0.0866,0.1638,0.1447
1,dino,simclr,0.7431,0.6191,0.6061,0.4755,0.1023,0.0658,0.1866,0.1129
2,dinov2_large,simclr,0.8719,0.6846,0.6582,0.5807,0.0667,0.0687,0.1215,0.1188
3,fastreid,simclr,0.6612,0.4463,0.5268,0.3712,0.0775,0.0542,0.1413,0.0941

### Visualization: SimCLR Embedding Space Comparison

In [8]:
model_name = "osnet"
X_orig, y_orig = embeddings[model_name]

simclr_embeddings = {
    "osnet_original": (X_orig, y_orig)
}

print(f"\n--- Training SimCLR for {model_name} ---")

head = EmbeddingHead(in_dim=X_orig.shape[1], out_dim=128, hidden_dim=256).to(device)

trainer = SimCLRTrainer(model=head, device=device, learning_rate=1e-3, temperature=1.0)

trainer.train(embeddings=X_orig, epochs=15, batch_size=128, val_split=0.1)

X_simclr = trainer.transform(X_orig)
simclr_embeddings[f"{model_name}_simclr"] = (X_simclr, y_orig)

--- Training SimCLR for osnet ---
Training SimCLR: 1307 train, 145 val
Epoch 1/15 - Loss: 4.7346, Val Loss: 4.9309
Epoch 2/15 - Loss: 4.6016, Val Loss: 4.8285
Epoch 3/15 - Loss: 4.5700, Val Loss: 4.7982
Epoch 4/15 - Loss: 4.5546, Val Loss: 4.7814
Epoch 5/15 - Loss: 4.5434, Val Loss: 4.7762
Epoch 6/15 - Loss: 4.5375, Val Loss: 4.7676
Epoch 7/15 - Loss: 4.5319, Val Loss: 4.7627
Epoch 8/15 - Loss: 4.5273, Val Loss: 4.7606
Epoch 9/15 - Loss: 4.5242, Val Loss: 4.7592
Epoch 10/15 - Loss: 4.5216, Val Loss: 4.7579
Epoch 11/15 - Loss: 4.5190, Val Loss: 4.7542
Epoch 12/15 - Loss: 4.5172, Val Loss: 4.7523
Epoch 13/15 - Loss: 4.5157, Val Loss: 4.7488
Epoch 14/15 - Loss: 4.5139, Val Loss: 4.7481
Epoch 15/15 - Loss: 4.5122, Val Loss: 4.7462

In [9]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_original"
X, y = simclr_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '337d8092-842a-4aa0-b647-7d3a595b169d',
              'x': {'bdata': ('aAK+vzDfCMAulF+/ijZov+BL+78n91' ... 'iYv5a4pr8Y2AfAMAoIwBA4A8DtSYS/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('Q2qmQNBbrED5d5ZAPzXmQC80qUBuH8' ... 'nuQOqi20CTFgxB9ksCQQvXs0B7AvNA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

In [10]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet_simclr"
X, y = simclr_embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

C:\Users\KM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': 'c510d55b-0d36-4bb2-8227-b92f2535fa0f',
              'x': {'bdata': ('lSrLP0sVoz/yA1lApKuLPxj2qT+bRm' ... 'AoP8KNtT6mGNk/ZurgP84/WkCO8F8/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('utrMQFf7xECTa9NAOC+QQI040EDVDj' ... 'uJQFOEnUDwKt4/pLRUQNgv0EDEpXRA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',