# Jersey colour classification in football video

In [1]:
import torch
import pandas as pd
import numpy as np


from dataset import load_manifest, get_loader
from models import load_model
from extract_embeddings import get_embeddings, extract_all_models
from classification_clustering import compare_models, evaluate_single_method, run_clustering
from visualization import interactive_embedding_view, plot_confusion_matrix_clustering

d:\Anaconda\envs\footpass\Lib\site-packages\torchreid\reid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings("ignore", module='umap')

device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
manifest_path = "dataset_v1/manifest_with_splits.csv"

df = load_manifest(manifest_path)

print("dataset size:", len(df))
df.head()

dataset size: 64291

,crop_path,label,game,src_image,x1,y1,x2,y2,frame_idx,player_id,role_name,left2right,split
0,dataset_v1/crops/game_10_H1__frame_001877__i0_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1399,522,1475,667,1877,101,Left Central Back,1,train
1,dataset_v1/crops/game_10_H1__frame_001877__i1_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1524,290,1591,408,1877,103,Right Central Back,1,train
2,dataset_v1/crops/game_10_H1__frame_001877__i2_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,1091,874,1171,1067,1877,104,Left Back,1,train
3,dataset_v1/crops/game_10_H1__frame_001877__i3_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,77,549,126,704,1877,105,Left Midfielder,1,train
4,dataset_v1/crops/game_10_H1__frame_001877__i4_...,team_left,game_10_H1,/home/anton/Desktop/skoltech/ML/Project/output...,185,169,223,269,1877,106,Right Winger,1,train

In [4]:
df["game"].unique()[:20]

<StringArray>
['game_10_H1', 'game_10_H2', 'game_11_H1', 'game_11_H2', 'game_12_H1',
 'game_12_H2', 'game_13_H1', 'game_13_H2', 'game_14_H1', 'game_14_H2',
 'game_15_H1', 'game_15_H2', 'game_16_H1', 'game_16_H2', 'game_17_H1',
 'game_17_H2', 'game_19_H1', 'game_19_H2',  'game_1_H1',  'game_1_H2']
Length: 20, dtype: str

## game_30

In [5]:
base_game = "game_30"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 798 H2: 713 Total: 1511

In [6]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_left     759
team_right    709
goalkeeper     43
Name: count, dtype: int64

In [7]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["osnet", "dino"],
)

========================================
  модель: osnet
========================================

d:\Anaconda\envs\footpass\Lib\site-packages\torchreid\reid\models\osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)

Successfully loaded imagenet pretrained weights from "C:\Users\Антон/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
loading cached embeddings
  готово: shape=(1511, 512)

========================================
  модель: dino
========================================

d:\Anaconda\envs\footpass\Lib\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(

loading cached embeddings
  готово: shape=(1511, 768)

### Compare methods

In [8]:
method = 'log_reg'
df_log_reg = evaluate_single_method(embeddings, method)
df_log_reg

evaluating osnet for log_reg...
evaluating dino for log_reg...

       accuracy  macro_f1
model
osnet    0.9637    0.8528
dino     0.9769    0.9448

In [9]:
method = 'mlp'
df_mlp = evaluate_single_method(embeddings, method)
df_mlp

evaluating osnet for mlp...
evaluating dino for mlp...

       accuracy  macro_f1
model
osnet    0.9736    0.9425
dino     0.9769    0.9448

In [10]:
method = 'kmeans'
df_kmeans = evaluate_single_method(embeddings, method)
df_kmeans

evaluating osnet for kmeans...
evaluating dino for kmeans...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.7095,0.573,0.7637,0.6295,0.7445,0.6142,0.8140,0.5871
dino,0.7664,0.626,0.9775,0.9522,0.9808,0.9793,0.7366,0.5447

In [11]:
method = 'hdbscan'
df_hdbscan = evaluate_single_method(embeddings, method)
df_hdbscan

evaluating osnet for hdbscan...
evaluating dino for hdbscan...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,NaN,NaN,0.9755,0.9509,0.9775,0.9567,0.9768,0.9527
dino,0.1509,0.1509,0.9775,0.9522,0.9815,0.9798,0.9801,0.9789

In [12]:
method = 'gmm'
df_gmm = evaluate_single_method(embeddings, method)
df_gmm

evaluating osnet for gmm...
evaluating dino for gmm...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.7095,0.573,0.9285,0.8038,0.7551,0.5556,0.7935,0.5761
dino,0.7664,0.626,0.9775,0.9522,0.7968,0.6533,0.8114,0.5901

### Visualization

In [13]:
df_viz = df_match[["crop_path", "game", "frame_idx", "player_id"]].reset_index(drop=True)

name = "dino"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1511 точек...
Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_30_H1', '1093', '201',
  …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_30_H1', '1093', '201',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABQADwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDPxS4p4UDml2ivibnmpERoqXaKYyndxS3GJx7/AJVz/jm/urHSC1kjNIxwSozgV00dhe3VrPLpyxXU8C7jbBv3jD2FM8PX2l+KopdDNrNZazbqQUdQNxB7+td+Fwcpe/bQ3o07vU8v8Kar4kn1qG3cSPAMmQdttd+4+bkUR2s1rJJFJGsckblG2jHI61J5ZPLZzXNjJpzslsRiIqLLoyKXJ9qKPxrmMnoHNMc4zn0p1NcEgirjG7BO5jeGo7pG8Q+Jo9Qkt7m1DfZlMxAO0ZGR0x2qn4Fuby48Uv4v1QLbWkgJleBAoBPHQHke9dJYS6RFBfaTfulut3CysTwc46gDr/jXCal4M1iFpBpWsRXWnshypcjk9QAOvGPxr6nBv2VGzPSoQuj0KW8s9TaS/splmhndmRh3Gf0qIIMdKl8MeHBZeHoI4riH5VG4OcFj3wBQ6bHKHkg4NfN4q3tGzmxKalqNAoK88VLx6CjjNc6OZ6kW01DfzJa2cs8hwFQn9KtNjPSsLxpMkfh+63ttylb4fWaQ4rU4DxDJJf3c12Lyb+6jBucYFZuiS6nHqlqY9SuERplQrvJ4zVOK/wARbC2eOtaXhyOS4ujPEVP2UCYg9+a+vnSiqOh1xquK0PYbOE2gCJKxCDAJPPXP86mIycnknrmq9nKZoFlyMsN1TZNfIV/jZz1KspvUN49akUFlz1rsPBXhnRo9I/4SrxZctFpkaZWJMkyt1A44GcY5PeuA8c+JLnxNOsHhrRY9Isvm8uRYlRyBnBYj2IrSGEco81wULq5ZnuYLVQ15KsKE43MRWB8QtGvdX8PGXSZEnjRvn2kYIxkfrXNan4F1++CSXmvMxK5Kl2IUnPHH8q09I0XWLKyaxl1dnt87mCswJP8AQcVvGFOkr31KjZHnbaFcR6HNqF1FJCyPtVGGMkEg81L4B1SKw1WUXJXyZImQkk857V6/9nh+zhHhR1A5VgD/ADrndR0XTHvke1tIIZAd7qFAzjnOPeu2nj3UXIWrM6bQ3P8AZ0YIxgcfTFXt1UrHatqgU9ulWlIwK8etrJnNLclu9Qur6BILxlMMYCpEpOzaM4yOnUmqyusS7Y1VV7ADAquS2eaQk0c0rbg29ixJKCnWq4YBjR25pnOelS3oO5IW3fKCBnua838e+evjC3t4LmZhKir8shG35iPy5r0Muo+8OK5XX8NrceoJpfnSw/LE5PyY7EjBzjrW+FaU9S6UHKVkdjEqxosex4yANyk5wanDccVDpqWM+mi5nvPLuSpYxZPXGcDj1pQRjg4rKsvfdh4mjKm1qf/Z'],
                                   ['team_left', 'game_30_H1', '1093', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABQACIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDMpCTR3psjqil2OAOpNfERXMzz46sqazPdw2TGxXdOeFGM1V8PtrwuJk1oLjAMewDH6fX9K3HgFr4am1u92wrI3lWoY/ePGT7jnqKrxyzOE89VV9oPytnI9a754ZU6V7HS6aULk+fpRTPworzTksNY9xWVr18bOy+1G3M8aSAug/u981pHJBFZt3N5e5HjyhG1s9MV04RL2iuaUld6nn/iPxdqniHVoruV1SytDtt7YE4RB2x+FeqRXmiSeHrG7tJTHPcOxlhc5ZMjg598HivL08GNNezTaS9q8UjnChwWXPPpmu40Xw9JZWMcWobZZc7hg42jsOPx/OvoMeo+x0O6rFKJtjOBzRUHkgcAcUV83ZHFZDmYYwKpa3cGDSriQKrDYeCPXirPWqWsRNNp88Zz8ynpTpS5ZImLseaJLc2krNZSvCScqV7V6X4bup7vR7aa4uGmkK/M5HNcL4V08a5eahbOfKMFs0kYAP3gWH9K6rwBIX0UrnIjlK8jpwD/AFr6HMZqeFUkdE53idHRSc0V87Y5LkdNK5Bz6VZtbG+uYpZ7e3Z4oV3O56AVymseLbK3gH2IefM2QoAPX6fWtKFJykUkZ2nRX3hnxLLf3Fl5tjcRsh8os2CTnnqfWug8Mm3FpKbWJ4o2lLBXBBHA9ea5WDxrqMl6LW7QKrkhRtCgZ45HqK7S1QxqRzj3Nd2Oco0kjabSjYub/aioc0V412ctj0jwVqFro3gC6nvmPl3yOoGOARnbmvLIdM0uK7WQWsZZCWyScZ61ce/1BdNOm+eDbEcLjOCO4qKz+zG4gS8ZltmcCZ15ZVPUj3rqjWaehd7nEeF7C31fxHPqtwGa1gdmi28Dfztz3ODmu7B3cjua7TS7L4O21o2mw3l5HmTf5+wgtnHrxnrXJakLGPU7qLTnkktEkIheTGWXseD6VWKqudkErkFFH40VxEn/2Q=='],
                                   ['team_left', 'game_30_H1', '1093', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgAEQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDEyfWlyaaDmlFfnR5Y+jGeooU+vSobm7gt0LSsFA9e1bU6bm7RGoXFupVhiZzwACa5K31u61XUks7SVlDNg7RyBW5Za7p9/qKWcsLi1d/Le4IO0dia6+28AroKPrOgzxzWzqMSMgJU4/OvYweFdLWoejgaCbbmR6tpEemWdo0czSiVfmJOcHFZo6VLc317dhRdsCUPGKiFeZjGnUdjjxKSqNRCiiiuSxkRMu08UAH0qZsZpMDPSnHVhYWz2LcxmYExBwXHqO9V/i5ptt4kW1Tw6q2kcSgMm3G/1qYrnilRGUZDEV04SuqU7tG1OXIc1rWptYeDIPD93plot0iEpNEnzYA6k5r0LTtQltvhLb3dtdEXDhEKN/8AXryj4iRW8Ws2bXbnaGJyoxkccVe1jxXomoaJYaD4aiuIH88CZXY5bHfJNfYxUatHmO+nKTWh1CSSSRrJKgVj2p4rZ/4R1LbwrDqKOQwGWj9B61jj2r4zFpxqM87EU3CWoUUUVzGaIGc8Ubz1prg5xTcVHtGnoMmWT1psl4kCM7sEVRliTwKjxWR4kult7XDKp3qVORnrXRg6TrVVEuOrNLwFd+GdZ1C7vfETI7K2IAx4x3OMHsK3YL/4c6demTSfDsc16OQwAAGOQTn3rwrVwjzM0ZwcnleKveD7uPTr0yzscEEEnNfbywcoUeVHqQrKEND2nU/Et5fkjAhjK7fLU8YrNRhis6wu4by3WaBwynjirG8ivjMY5Ko4y6Hl1ajqO7LW8UVU8z3orluZ3JXHPOaTHsanbb3qM9c1GgxMD6Vzms2kur6qthb5MijnPT9K6m2tZr2YQQKzM3HHbPeqMul6x4BguprqwWea6+bzUBZgPTI6V62Tpe15ux0UKblqeWa9Aum6nPaMVZoTtY5yKzWm7D5iewPWu80Pw1DfX81/fs0iTNuZXHzGtzQ9C0LSvEEGox26SY+XZIPug8V9HLNY35HudUeW+pY8B+D9ci8Lf2vcxeVAfmWJh8+D3q40R9q9INw7Wc7m5i8powdq9FyPrXn8+xJHUNuAJAPrXz2aJX511MMZCMUnEreQfUUVJvNFeUcIMpOCPWm3GLeA3E7rHEvVmOAK0dP0HxDqVo13p2l3M1tH8zzeSSmB1we9eVeMNX1HWdQOn2iySJG5QRovVh97P0PHtiu7CYT2kk5bdzeC11Op0n4kQafqZjtrQPFI+zzDySv07V1OqeI5NatizvN+9ALiRsjHYYri/CHhGGyt1vtTeOa4flYwcqg/xro2iRRhMAV2Va1Ok7UjX2rjoimRsBI4+lZ2qs3kO+9htQnj2FaskR28c1m6vCRYykgg+W38jXPBuVZSMpSbZieDdY1i41RoGvJGtMAGMsT0B/8ArV24IwOK4LwKpS7kb0b/ABrvo1OM1rmqbkrCqSctx42460UuB7UV5PKY2PeNH8RC2+EWnX1jaRQRkeTPDEQvAJDEkdM45+teC3qWC6nc3NlaJbmWRm46gH3rs/hp4usoLK40HXJoksjBJsDAHB2k/hz0rgXcE7kOVPIJ717DrWwkYXN2yR3zwTTS7dqjJwc4qaMgjpXlN6kNgjYHNdN4S8KweJAyPEZVDbSBIFH8+a5abPYUWOoapYzb7C8mtm6kxnGa0pVOWVxcx6/Z/BTRYraSW0s2imI4KynGfpXEeJPC2saFKy3Fo7wA8TIMr+PpVGP4ieNrdAF1KRsdCepqT/hafjN4/Lcg5/jwcmvTliIVF7yHcztjn+E/lRVG41C7uZmnkBDsckAd6K4Xa4rH/9k='],
                                   ...,
                                   ['team_left', 'game_30_H2', '143027', '212',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgAC4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCttHrS4xSjHrQcV+RSlc8kQda8q8X+IL6bWbiCKeSKOJ9oVTjpXrEiNBZG+nHlWoOPNfhCfTPrXE6/pXgrWL/dF4iihunYearZwT1xkV9BklG0nKcdDrw1Lm1Zt+DZ57jwzZTXDM8hQ5Zupwa16qaObEWaW9ldW06QqADC4YAfhVyvKxkZRrSurK5hVXLJhSgbiF9eKdtFaum2uhTWavd60ltdbuYyfujPXNc9Gk6krIIQc3oY/wC0rYXtj4D8O2kVwkVrCu6WJcBmc4+9Xlvw1sfD2ptqK65pGoXwiiDpJaRs3lEdS2O31613nxc0/wANT6Pc6lca5NeXix7IsT7gWUdQDxmqX7J9/fweLtS0622PZXVoDOWQZ3blCdemec5r9BwijDDrQ9VUvZpFLxNa+GfC+k22q6BNriXonQG2u7MxpIhHzYbvXWQOJbeGZcbZY1kGD2IzUv7RN5e6j4RjiFrHcKdflt7IxphlWMEYyPfNZfhiO5j0K0t7uFoZYYxGVPXA6H8q8POaalSU1uceJp9TXIySPWqM9haFxI8S993uKv8A8XFZviaZrfQr24XG6OLIJ9Scf1r5/DRlKqorqcsL30PGPGyPN4huzB5n2TzS0a5yBXVfBPx1pXgTU57u9s5Z/PZPNCtgbFPQcHnNZgja4jH2gDp6VB/ZcDNtZOK/T6WFUaSj5Hd7SXU9NudVk8VWtuNJuSuj2Woy3UKycyNJJy2SO3tWoPNPzSPuY9TXM/DrZFBdWq5AQq2O3PH511ZGR0r4POZzhVdHoc9ScmKKzfiFPBYfDi+muEJe5njiix6g5z9OK0RXnPxk1O/iFrp93HINNyJoHxlWfGDk9vasckj7TEa9CKKbZwt3rUqsCCwGfWn22vSNgYYj1rU8CeFH8RXbXFwrpZJkKynG7I4xWRc2P9nXs1tMpRo5GXDdevFff0sdCVT2fVHT5Ho/wtvPtV1fITyI1J4967phjpXD/Ca1EOn3d4MHzZAgx2xXcZz3r4XPpc2LbRzTepHu78VT8WS+HtS0aPSby+s2CsCUc/MG9qt8HivDH8y98QfZVDvM90yqM8nDn+laZJRjecn0QUXY9ssLeHT7VLO3AjjjHyhRijUfDXgjUtPutW8TT3EVyjABlI24x9OTxS4+VRyMKBj8KyPGGl/2norKoPmwESrz6fzrDCYuUcYm3o2aU52ndl7w5YaPZWDDRLqW4s2ckNJjOfw4rU+U9DXnfw0keHU7q2GFV49zAnup7Cu9yOxozdSjiPJk1tZXRPoljdatffZbVGkIDMxVchcAnnHTpXlfw2sEuvFupagw3rbl9nPQluv4f1r6G8J/ECz8O6AljF4bjaTJWaZZQGdW4JxjPT3rktcfwhawwp4T0+S0SX5plKhSD/tcc/ma6MHOjRw0rS95odPl5Sljj2pcenSoPODEYP507d8owa8G73RmaFpoqX0mn29rZRQ3Fys/lXSrgNIOkTcAEtjjnrWbiRSVlRkkU4ZGGCp7g1ZvdWu4vCt3psBKymZLi0lUkNFIvoR2NQGaW5Y3Nw26aX55G9WPJ/WvSxdZVqUH1RpNppH/2Q=='],
                                   ['team_left', 'game_30_H2', '143027', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgADMDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBduDnNNkUke1SZpK/LmzziFU55p4QUpODTbhNQGnTX8GmXVzaQMFlljTIU+hq6NGVaVoocYuTsY+p22uX+oC30k+VEo+eRuBmtc6TNpsEYuL/7TK/J/wBmr2g+J/D02izRWMUzXtsxe4EwxkH0x9P5VBcamt/CpSIIg5HXNe7i4Ro4ZRa1PSrRhGiktyttHrRTSTRXz55tizUZc1JTSBmptckjkl2I0jFQFUnLHAHFY3irxl/wjXh+wsPDl/N/xN7Z21FJU5Dg44z2rcltJ7uzuILKAXN46YggLACR8jAJPAzXnHxch1XxN8UBpNlp0UN3DHHAlrCoVYjjn9TzX0/D9FJOcjroQuWfg3K03jFri4UNZJA7XGR8pUDoa7oSwzJvtl2wsxMY9s8V5pqNx4y8J6MfDEmnxWTXRyZkXc3UcbvT2r0PRoBDpdsjNuIiUE++OavP+VxiojrwknqT/hRU2V9RRXziSOfkYzcc9KTcc96aWzQKzRkYfjzUrzTtFE2m3L2935gMciH5lx3FcD4G8Wt4W8cL4h1VJrx3RleRmy+T/Fk+nvXT+Prvy76GFhlDECD75rg9Q8qYk7elfe5NQi8JfuddCpy6ntdxrPgzx5HE8+oBGjkDrkjIbuPzxWuPD96oPkSR3KDoyHivFvh1a2baq4nXLEblAOMkHP8AKvUo3miXEM0kKnqqHArxc0jyVOWR2VqsJrUkcFXKsMEHBBoqIkkksdxPUnvRXhnFp3H0Bx0ppbHWmhQeea5VdnKjhvi7HJbW9rqiKCgPlMCfXpXng1JH6r+Neu/EXRdQ1bwywsoxIiNkqeAff68V43Jpd3AJGlt5EWJsP8vC/jX3OS4pU8PyyOinFtHfeDdDa70G58Q6bcFp7ZiZIQTwo64P0r0Cwukv7WO8iDqkgBAYYIryH4feJ5vDupsUjluLW5UxywL/ABZ9PfivV/DZ1O50NdQv9JXTIS22CMddueCfeuPOYKpFzRpUpPl5jQxRUfmiivl7nJdDXUnkdaz9e1SPSNOe5fGQPlBOMntWjPHcrayXkcEkkUIJcqhIH1ryTXrrVPFut/YoFY26yYJH3QB3xXXgML7V88tkEEdHofjrV9Xs30uBIlcruZRzj2FdPpehwWtjItyY55bjmXABGe4HpVfwz4esdFs18lI2lYZeQrya2EwWJPB9a0xmMTdqOiRs6jSsiomh2CRk2sVtBOo3RPI2OfTnrWpcanqF9Asd1b+WoAwcYDEdxXn/AMXLt4bSwhRiA7Oxx6gDH86m+FE+pz6VdT3tw8tsGCW4Y5x6mu6lF/UfaVHuX7aXJZnXbG9RRSmT/ZorwWjnv5HX+DPiJB4e0mXRLrSmuIJ3bzJI3AbDdevUVqL8ONBvPDDav4FXMkrGV4GYF+eSuOx5rzIxBnyfWrlldX9gf9BvJrYBt37tiOe9dmExShB03sTGRJLDJFI8Ug2MrEEelROmAQvWkaVuWYsWJyTSSToEOG+bHGOoNc/ImO55x8WZmn1LT7CNiXCdAD95jgfyrvPD1hDpOg2WmglWiiBkBHVjyT+depTwfBq31PSfEspgvdUsrVLYQqrdccsR3bJNLqsHwV1CGa/tb26sLpw22OJ2zuPONuDnn3r6CVOM8HGF9jZJWsec/J6UVKkfyjMR/HP9KK8KyIP/2Q=='],
                                   ['team_left', 'game_30_H2', '143027', '214',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgACQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDPCkjOcCuA+MElwkdjGGP2ZtxPpvH/ANavRYYXmkEUSF3I4A9K5vxXeeDLkjQ9c1J4lc5Z4ULlGB9RX5vlFKp9YjNRujzaUbs4D4XzzjxZFHbuwjkjcTAdCoHGfxr10cHIJFcTozeAvCWoyyafr13fzzARfNCcbOu7NdnY3FnqEBmsbqKdB12tyPqOtehnmGnUqqcVoa1YMedzHNFOA4or5lxOc5L4k+I7zS4INFsy1v8AbIjNczDhymSFVW9OCTS/Aa3ttX1270v/AIQ0eJZZY1YZcAW4BOSSSPvEgVzXj7+0/EPieU4jkFtbiGIL0WONSf6k1L+zv4i1PRfipoEVhdvBb6jqNtbXadpI/MBwfxr9GwFKNLDKMd7anfRikjuvH2iafc/DbUdetPhzPoYsLwQPeC5yu5ZPLY7d2CM5GcV5FoeqXOnazBeWU5hZJF3kdCueQR3GK9y8Wapqknw7+NmjXdyXttJ1uGG1jz/q42uWcjPfkmvE/BlvZ3Ul8086edGqvEjEYkGfm/GuiDvFqZtJJnt0iqXYoVkUnIZDkEHkYorJ8P3MD6VFHH8qw5jAJx06fzor4mtgZKpJLucTpakdtoGnwTTSIrmScMjMzZIDdf515BaRzaF4ghuYUKzafeLKgb+9G4IB+uK9ybDZBGRjkV5p4msbZdevy8YUGZmwTjrzXs8O1ZVasoyd7oKM7Mm8QfEy91T/AITuFtPhhg8XXEFxOAxJiePrj1BrF+H2gWet3dybp3iW3VWBQYJBJ7/hUEsNkrZ+T6V1Xw4a2hvrpIwCz2+DgejCvezOHscNOcXqbVJ6HZaXpem6dZrbW4kKA5JkbLE+tFWAeOlFfnLx1Vu7OX2rJAwBAKhh615t49gubTUpbm6VltrlyYZNvBOOVz6+1eig46VzHxa1CA+DYdLlt98zXyXEE2PuAKyun45U/hXpZDiPY4qy6lUrN2PIbu5fzMg8eorv/gxG7z6lcu2VESJg+pbPH5GvPpIJJgREhbZyfp0r23wHpCaT4ZtkXiWf99Kc9SRwPwFfV55WccJJdzWotLG6QM0UnI4zRX5vqcvKNGOaz/FOmw6pocls6b5FO6M+hq7mmzhmt5NhIk2naR644rpwknTrxku46b1OK0fTdN0+S5N0I0hMRX5u7ZGP611Xh+eU6dFE6PhFwjEcEdq5eSeDUre6trgqksqEDHZv6c1c+GqOdHuHe5eTE2zY+cpge9fYZvZ4aTvvY6qh1atxRTQKK+IOcbmlB4pCKADQm7ma3MTUdX0HRdSt4LzR0drgEz3A/wCWaM20sPcda7GfRvD2k2f2bw84kt1clmUHnPQnJ61LH8L7bxl4ci1PWdTXSYIbqPyHLLm5Qn94ntwODxgisXUNFHhXXLnTrDUpL2ylVWjD4yvOMH34r6nEO+Xpt3bR6UbeybZMwwcYophkY9UNFfM8jOE//9k=']],
                                  shape=(759, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '875a10be-a9e6-446c-96d1-d12e8520ae3d',
              'x': {'bdata': ('1g0fwMZ1Wr8DWjzAhvA1wGT5qr/PCZ' ... 'hMwILu/7/cUNK/lj10wNuTS8APGZbA'),
                    'dtype': 'f4'},
              'y': {'bdata': ('7tRgQVlpVUGp01pBH0FYQTF1ZUGTGE' ... 'FEQXg4P0FKcWRBNNNPQWgCVUEzLUBB'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_30_H1', '1093', '100',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA8ABUDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBsiO5Ece4yPwgUZJPoKx/Dt3LJdS207yG4jJWaN+sbA9MV6x8DtLhu/E9xf3AilisYC67hnDnpnt0ya0viB4R8Mzafqfi/RVEN4x33EYwQ/wAwBI9PXivmcJgHLDSqLscsIrlPNM0UmeOvWivH5JHK9xkXibxX4aEknhi1aXzY2a5KjcwUAgEDuK9Hk1nQ9V+CsmqvcQpfT2v2Yh5Np+0bhkAd6r/Aa6sIPF14l80S+ZYhITJjBJYEjmuq8XeE9O1LwbrNrYWSiaGc3NpHEwALYXkDtkBvrzX2WU2+ptHUvhPFrZFWLY0hbaxG4HOfyopUBRFDgh8fMO4PeivnKsHzs5HuS+H9WfRNcsdTSLzmglDeUOsgwRtHvzXqNj8S7W1S3nvfDepW98S7G2Qjnk7CQTwCM/TNch8ItHh1rxhGJ/mh0+M3MyBC2/sqnHqSD+Br1rxvrdn4Z099Tmsrdr+5ULEWAzGOoG0jJ78CvcyRyp0W5bHZBpI8J19t2tXlxNZT2f2iZplg3coG5wSODRVfWtUudY1OfUbzaJZmLfKMDH0orjrVKTqNnO3G56j8D59L0Xw9JdTSr9s1C4xMdwPlhchAfTIya5H4wQarF4wnku8NazEvavhtrRk5GM8Ht0rhw8sDNLBNJFInRkbBqy+sahqNmkN5cNKisGXJJxwR/WlTxbWHcUh82hGTg8UUgorybmJ//9k='],
                                   ['team_right', 'game_30_H1', '1093', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABeAD4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDJ6UmajDHNPHSviFK55o4EU8HHIqIVoeH9Kv8AX9Vh0vTIzJNKSC38MeBnLfhW1KDnK0RxV2eXeKta1621maKKZ1TeAgIOPxru9LadtPga5IMrIC2PWuz8ZfCfWdNvLdVtEvVkAJeNd21u36gdM/hXMSw3drI9nexmOeE7WQxlCv1BrtxNBwp3aOirQ5I3AHFGaQc08YHavNRzFMdaeOlMByeKkA6VMbWAciK7qjS+UGIBfGdvvX0N4U0my8F+E7ebS5IblJk3zXAOQQR0+vBr51m4XPar+hLdajaT6N/ajw/aThQZWG07SMD25Ne5k7gp3kdFBI+nPDniaw1cK0sgQx8BGBAYD/69eW/tB2li3iLTtQs3jL3MRSZV7FehrrfhfYo/gmytdQQLcW6+U7DI3YOAfeuP/aA0mBb3SHtpmjmyd4wQMH+de7mVGnPDysbV37p5m67WopNrDgnPuaWviDgKK/eqYHioRT16ipiimPI3DFb3gLwvL4k8TW+nRzm3wN5cdQeSP1rCVgvJr0f4HPd2viCbUI9LluoEi2mQfwHnkevpXo5bd10ka0T0b4beEJ9HsZ1k1CS9kWVg0bNnvx/u/nXD/tEzSx+JrGFjlRAWBB4U+1eoeG7oQX0ktxFPH9ofJJOEQe49Sa8q/aVdz4ztF8twn2f5Wx8rfSvpMwbjSZrVeh5mrbvmNOzTE6U+vim9TibKQp27AzUix7lxGjMxIHT1OB+tehfD74Varqs41DxEf7N0uMjAkwrzAEZxnp+I5rooYedV2RtGNzzmAvcvsgSSVs4wik11Xhv4m3PgaxSyurAvb72Z/wB0AQP9on34Fenan4w8EeF1FhpWlRyyxEszOvU4PXA9TXz54xe58Q+Jbi88pUtpJCwVBkKD69K9WhGODfO9zaNon1L4E8Qaf4t8JRa1pquschUSxSbQyHd1IzgDvWD8e4tIvvC8Fyb2Ca+spMxoGycEbSOPrXhFndXmm6TJZaVM1oZAFMisR36ZzgVUlsvE1gyz6ql09s/R2YsnPfNdtXF+3pNDkuZF5KkpkYyBUgU96+TktbHG07m/4P1rWNJ0qa702xgdbeVTJcvCNyDsFc8jkjIHvS+KfiB4h8QIYLi5aO3xgohK54HXBx1Ga5yz1W7s9PubGIr5FyAHBHoQcj0PFZ5lwea7I4yVOnanv3KUiWBFjzksxJyWc5J/GntHk8HGahR9xqQNzXK6k5/E7hzEkJEU0ZIVlEisQeh5FfTdxbWGp+BJbSa1iYPZ712IOTtzgV8vycgZr3v4G62NS0L7DcMXmtSV5/u9v0xXtZTad4s1jJ2PEQogd4tpXYxXB6ineYvetDx7Glr4y1SFUKL52QPqAaxN2RxXmYuChVaRi2VFYng0vWmJ1p4rlIFXg8U7n1poHNOplCM2FJJrs/hJr50nW5FUgtMuApB+b8q4xgCMHpURDI2UcqR3B5FdmDrujO6HztHp/wAWdK1TVb0a5Doc8YVdsrgfK3pj1rze3lVwxUnIJU7hggjtXS6J8UPGWiW6W0N7BcQAAYniDN+eM9KydZ1ltfv21B7W3tnYEMkKBVyCecAAZNbYuUKvvJak3P/Z'],
                                   ['team_right', 'game_30_H1', '1093', '102',

In [14]:
model_name = "dino"
method = 'kmeans'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=False, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         747          12           0
team_right         14         695           0
goalkeeper          1           7          35

In [15]:
model_name = "dino"
method = 'hdbscan'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=True, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         744          15           0
team_right         13         696           0
goalkeeper          1           1          41

In [17]:
model_name = "dino"
method = 'gmm'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=False, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         747          12           0
team_right         14         695           0
goalkeeper          1           7          35

## game_40

In [40]:
base_game = "game_40"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 740 H2: 712 Total: 1452

In [41]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_left     705
team_right    694
goalkeeper     53
Name: count, dtype: int64

In [42]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["osnet", "dino", "clip"],
)

========================================
  модель: osnet
========================================
Successfully loaded imagenet pretrained weights from "C:\Users\Антон/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
loading cached embeddings
  готово: shape=(1452, 512)

========================================
  модель: dino
========================================

d:\Anaconda\envs\footpass\Lib\site-packages\torchreid\reid\models\osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
d:\Anaconda\envs\footpass\Lib\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(

loading cached embeddings
  готово: shape=(1452, 768)

========================================
  модель: clip
========================================
loading cached embeddings
  готово: shape=(1452, 512)

### Metrics

In [20]:
method = 'log_reg'
df_log_reg = evaluate_single_method(embeddings, method)
df_log_reg

evaluating osnet for log_reg...
evaluating dino for log_reg...
evaluating clip for log_reg...

       accuracy  macro_f1
model
osnet    0.9691    0.9477
dino     0.9725    0.9320
clip     0.9588    0.7060

In [21]:
method = 'mlp'
df_mlp = evaluate_single_method(embeddings, method)
df_mlp

evaluating osnet for mlp...
evaluating dino for mlp...
evaluating clip for mlp...

       accuracy  macro_f1
model
osnet    0.9553    0.8221
dino     0.9759    0.9524
clip     0.9863    0.9758

In [22]:
method = 'kmeans'
df_kmeans = evaluate_single_method(embeddings, method)
df_kmeans

evaluating osnet for kmeans...
evaluating dino for kmeans...
evaluating clip for kmeans...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.7479,0.5677,0.9174,0.7976,0.7231,0.5449,0.7762,0.6488
dino,0.7431,0.6061,0.7707,0.5677,0.9821,0.9786,0.7417,0.5516
clip,0.7342,0.5933,0.8492,0.7149,0.7638,0.6393,0.7576,0.5603

In [23]:
method = 'hdbscan'
df_hdbscan = evaluate_single_method(embeddings, method)
df_hdbscan

evaluating osnet for hdbscan...
evaluating dino for hdbscan...
evaluating clip for hdbscan...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.1123,0.1123,0.9449,0.6420,0.9415,0.6396,0.9421,0.6401
dino,NaN,NaN,0.9807,0.9746,0.9835,0.9796,0.9814,0.9750
clip,NaN,NaN,0.9835,0.9796,0.9821,0.9755,0.9821,0.9755

In [24]:
method = 'gmm'
df_gmm = evaluate_single_method(embeddings, method)
df_gmm

evaluating osnet for gmm...
evaluating dino for gmm...
evaluating clip for gmm...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.7479,0.5677,0.9483,0.8557,0.8843,0.7555,0.7727,0.5687
dino,0.7431,0.6061,0.7879,0.5766,0.9828,0.9791,0.7466,0.5547
clip,0.7342,0.5933,0.8712,0.7375,0.8430,0.7090,0.9594,0.8859

### Visualization

In [25]:
df_viz = df_match[["crop_path", "game", "frame_idx", "player_id"]].reset_index(drop=True)

name = "dino"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...
Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '55d33b88-7a50-4a0a-8452-7d33dd875d24',
              'x': {'bdata': ('arLSP5ud1T8FmeI/zptzPat/1T8//b' ... 'R/v9GUfL8HpBHAhnaMv8Wt5D/TZMK/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('JcbOQAcKz0B69cxAGNK/QMn7zECjF8' ... 'jBQJw8ukAartpA87q2QBI5zkB+dt5A'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',

In [43]:
model_name = "dino"
method = 'kmeans'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=True, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         685          20           0
team_right          4         690           0
goalkeeper          1           2          50

In [44]:
model_name = "dino"
method = 'hdbscan'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=True, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         687          18           0
team_right          7         687           0
goalkeeper          1           2          50

In [45]:
model_name = "dino"
method = 'gmm'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=True, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left         687          11           7
team_right          5         680           9
goalkeeper          1           0          52

# Video

In [15]:
# from pathlib import Path
# from make_dataset import build_dataset_for_game_video

# game_dir = Path("./output_clips/game_1_H1")
# out_dir = Path("./dataset_video_v1/crops")
# out_dir.mkdir(parents=True, exist_ok=True)

# df, bad, csv_path, video_path = build_dataset_for_game_video(
#     game_dir,
#     out_dir,
#     video_path=Path("./output_clips/game_1_H1/game_1_H1.mp4"),
#     players_csv=Path("./output_clips/game_1_H1/players.csv"),
#     min_wh=20,
#     jpeg_quality=90,
#     pad=6,
#     frame_stride=2
# )

# df.head()

In [16]:
# from pathlib import Path

# out_root = Path("./dataset_video_v1")
# out_root.mkdir(parents=True, exist_ok=True)
# df.to_csv(out_root / "manifest.csv", index=False)

In [68]:
manifest_path = "dataset_video_v1/manifest.csv"

df = load_manifest(manifest_path)

print("dataset size:", len(df))
print(df["label"].value_counts())
# df.head()

dataset size: 10157
label
team_right    4973
team_left     4840
goalkeeper     344
Name: count, dtype: int64

In [69]:
embeddings = extract_all_models(
    df_match=df,
    game_id=None,
    device=device,
    model_names=["osnet", "dino"],
)

========================================
  модель: osnet
========================================
Successfully loaded imagenet pretrained weights from "C:\Users\Антон/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"

d:\Anaconda\envs\footpass\Lib\site-packages\torchreid\reid\models\osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)

loading cached embeddings
  готово: shape=(10157, 512)

========================================
  модель: dino
========================================

d:\Anaconda\envs\footpass\Lib\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(

loading cached embeddings
  готово: shape=(10157, 768)

In [70]:
method = 'log_reg'
df_log_reg = evaluate_single_method(embeddings, method)
df_log_reg

evaluating osnet for log_reg...
evaluating dino for log_reg...

       accuracy  macro_f1
model
osnet    0.9818    0.9829
dino     0.9847    0.9895

In [71]:
method = 'mlp'
df_mlp = evaluate_single_method(embeddings, method)
df_mlp

evaluating osnet for mlp...
evaluating dino for mlp...

       accuracy  macro_f1
model
osnet    0.9833    0.9885
dino     0.9877    0.9915

In [72]:
method = 'kmeans'
df_kmeans = evaluate_single_method(embeddings, method)
df_kmeans

evaluating osnet for kmeans...
evaluating dino for kmeans...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.8122,0.6736,0.9602,0.8741,0.8636,0.6437,0.7550,0.6405
dino,0.8216,0.6414,0.8536,0.6042,0.8556,0.6059,0.6462,0.5270

In [73]:
method = 'hdbscan'
df_hdbscan = evaluate_single_method(embeddings, method)
df_hdbscan

evaluating osnet for hdbscan...
evaluating dino for hdbscan...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.2674,0.2567,0.5360,0.0649,0.9538,0.5236,0.5241,0.0548
dino,0.4472,0.4395,0.4389,0.0427,0.1796,0.0237,0.1849,0.0239

In [74]:
method = 'gmm'
df_gmm = evaluate_single_method(embeddings, method)
df_gmm

evaluating osnet for gmm...
evaluating dino for gmm...

,accuracy,macro_f1,accuracy_umap,macro_f1_umap,accuracy_umap_pca,macro_f1_umap_pca,accuracy_umap_pca_scale,macro_f1_umap_pca_scale
model,,,,,,,,
osnet,0.8187,0.6824,0.9602,0.8741,0.8658,0.6452,0.8251,0.6939
dino,0.8222,0.6421,0.8536,0.6042,0.8556,0.6059,0.7091,0.5614

In [75]:
df_viz = df[["crop_path", "game", "frame_idx", "player_id"]].reset_index(drop=True)

name = "osnet"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=1500,
    preload_images=True,
)

Снижение размерности (UMAP) для 1500 точек...
Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_1_H1', '80', '101',
     …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_1_H1', '80', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABVAC8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5kIPcUe9Pkzyaif7jY64OK4XFM4dx28Z4OaQk5zkYrLt5ZftQVievStQ9Ae1DVjRxsGfc0Z9zSZozUkE8gyDioDwQD3qxTAF81SegIzn0zVrcS3Q7+z441WaRSJHGQCOSKlvdPntoY5nACS5256/lUms3LDVTlGUpGDEMcEYqfVZZrnR7C8lkyXyAo7YredJJXPaqYaHsVJ7mP3xRimu2DnFKGGM1ztWZ4z0bSLG8elRswJ6HHeipra0kuQ3lAMVUufoBVJO+g4LVBeXrTp584A2R7Rj07U9ZvN8PWcf8URYn3B6YrNvWC220gguSAPpT7Pz5bT5UJjQcnHAre7a1PfceajduwjEHpSc4oPBxRXPLQ+ek7S8iYEZHeuktYo1RILSRSxX94Qec46VzRbaM9qfZTBHLROyuDknNbUpJPU6KNJzTfY2L7RSFU3CFE5APrmtaOygg8OXUQVUJTMZ459awb3Vbu7gSCeQlU5BA61myX1wCqvMxjUEBSe1dDnBo0VWUvcvoQuDk9gO9FDyI67lBANIORmuGer0OetScJJMexyMDqait0ZZCRnBqVwCmd2CBxTEll27CF2g9R1NB1UJckHbqT7znkcUyVN6EEeuKAcjOMU3zT2wKpanPTcea7IIFKqVPUGpQcDGKaqtuYnnNJn2pM0xElUaaJpEA6etIFHWiikc7k7IdTdoHSiigkcuQOtRsOaKKBpn/2Q=='],
                                   ['team_left', 'game_1_H1', '84', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABSADEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5qIXBIHaoiwB5IFTHpWVqqy7wYyQO4FcaSOKKu7F7cOxyKbVbTt/lHdknPWrRxg0mkW4NCAmgdaTmjmoIs1uPopmfeigC1k0SQq0Qlcfu8/maQ4wcnAxzUmrvKh0+3Kjy3jwCOxz1relFN6nXgqSnNX2LOjaUb1wqKY4j1Y9qo3UYinkjQ7gpIz64q74Wnkl8Qrp88jLDhgQDjjHtWddKY7qWMEkJIRk9+a1qRSWh6WMpwUHyoYaSgk4ppJwa5rI8Ju7HUVHuPrRRZCLRJIIPQiormVlaOZiSU5BPIApSx9asT2TvaRTniN5NnPYVcE29DpwsmpaEWk6g0fiJbyG3MjAH5B6Ec1Nq7l72aUIIy5zsByRxWP8AaDDfs8BIJOBjjHatddPuv7Ik1G5yuGCgHqc966WnbU9XEpOldvUo7j60mT60UgJzXK9jwRaKKKkCZfvDJwM8mujt2iuUKRSJ5cSgbSc5J71zOabY3JhnYR5Uk5Jz1NbU5qL1OihSc27PY3bmztrSYLtXzHBI4zj0q7e3VodFksWfzJWAYc4wfwrAnuJJ5PMkO5uhPtVa53E5UnI6GrlVTZXM5Plkx0qKpx1qFeWx70yKZnJVuo708dcisJvsRXo8uxJt9qKTcaKyuzlsxpJwagMbtKNgwxIAHqatAKCCRwDmm3OCQU4OeoNbJHbh5crvcVkeIlWIDA4IJ6UBicZPemKGY5YkknJJp4A9KTSIm1z3RCQFfKjBJ5p/+FOKKeSOaUquDijc0nVU1YiyfWinbaKVjGyHt90/Sm/8s6KKpEocnQ0tFFDJXUKB0/GiikOIuB6UUUUGh//Z'],
                                   ['team_left', 'game_1_H1', '84', '104',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABEAD4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDkyVAJOAB3pm4E/KQfoaoa+0w0q4+zuVYxkA9cDoayvBQ1O4uRAQ84JCggDqTj0+leElcmlQnVdoK7Ow0r/kJWrY5EyH9RXqX7TxPm6Kx5J80fTpXm66de6ZrtnBeQsjGZCc9gSK9E/aZcm50lSMAGXB/AVpS6+hFSlOm7SVmeNjrSt90/So9zYJz2poZjwT+lc8lqQ9B2aM03mjmpAuvGsilGAIIxzWvoFtFp9gL60cLKk4YrxyAB0/PFZYySMde1Ub5NQW9jNrKyRAjJGDjk+v4VvB6nfl2L+q141GrpHqUfiLS50kOuqfPlKG3kwDtIxgEjpyKtfH+9i1Sx0K+glWSN/MywwQTgfl/9evCvEt/q9jKwYNLbuDyAOM9wMe9emeERbav8O3s9WuCl1ATJbZPGSMkAfh0rrpUXNvlPWzTFYbG0+e1pI4t+MgdKaKc/32UckEjP0NNHeuKaak0z5hq7uLRSdzSZqGmUQHxJp2R87AkZIxyKt2Wo217IEilAJHQnBNcDqMkZu3aIKqnJAAqvDdSxTrMjEMpB4747V1Qp9yW0d/4hmVbcxAK7ONoJPA9+Kj8H3M7oLd3ZlDEhhk4OPeuVtPE0VxNFZXCFZNwXzOuBnGPrXQeOb1PDl3GmjSGWAjJY9ztya9OhUVNaIuzaszXuowt0wUnAJ61GAOa57TvEy3KB3A3nlsn86vjV4du48CvMxEW5NoPZtLQ0sDmm1mHWrbBO/nHSo/7bt/8AJrHlYtjjmkyDz2qIt/nNReYCSqkcU5Ru47njNdzjbUh7leSAs++M7WByCOua29Vv11LSrVlDZiJD7vUAVBosEEl0rXLbEQhsevPStTxP5VnaNFb2yxRTyZGc5BB/mRWsFdNmvtEo26nPRuI/u4Azk1uac0VxZOsjZfAIIPTPGK58DpUsUrxKVjJUE5IFY6N3FGppYldyCfmyM4x6c03zTURPJPcimUcqZm2kZulkyTvuYnHvW0AAgI65FFFaS2KlsT2oAuIwBxvH863PHv8Aq7cf7bfyFFFa0/hZmckCc0/NFFcyAQk4NNyfWiigTP/Z'],
                                   ...,
                                   ['team_left', 'game_1_H1', '2994', '109',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABbADEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDkWTnPegLxinnOOlAFfPnFdjMY4owG6nBFPI56U6JN7hQBknHJoKV3oLC4Ugbhn61binXJUnjsaup4YaSAzGUA4zjaef1rHkhaCUxsehxxUSZvLCzUOaSsjQ8xaKqZHo35UVOpy8hEMEUHaKZhqUAnrWpYpIxVS8ulgRiDyOeKubeDWRqpUShGOATzzTjua0Y3mrnZ+CPE1i5SPWI5hb4wXUZA+vt9K7PU/Aulazaf2j4c1NJsjJiY4I9etcN4ZGn2VoskllDdAAEbmfjv2OPwrZ06S/tLhNS0m3ECsdzKpYKefQ5PSr5UtT9DhltGthVKPbXsVv8AhC9e/wCfc/8AfQ/xorrf+Eu1f0i/I0UtDw/7MoHle+gsO1RjNBqD5MlTLYC8k8AVX13Qbg2rT7wABkjPIqxaOI5VY9Ac1Y1W5ae2aNGJJGKWt9DpoSindnGaXqOoWl35SXLBAcbSMg/nXsejaxdNBDbrwTGOSOvFeTad4e1K61TNvBJJkjIVTx/9avZfC9rNp93CbuB7Z0ixzwQcdecVpaa1tofp+X4jDzy1wcknYi2Xv/PMfkf8aK2f7am/6CNx+Q/xoqOY+f8AZw/mR5DzQDkZHSovMOMZx9aVZOACMYpXPh7EmeKfECXCjqSBUBk560sEhaUbTjnrT1Kiruy3Poz4JaKBbLNIqhcA5OMHj1NXPjZqdrZ2EsH2OBiE+Vy3fHYCvL9E8Y61oekrHbz+ZCBwoJBH5e5rB1Xx02qtKNUDTuRg5Yke3B9q7Y4qChy21PdwuDqXUW7N7GN/akvov60UfatI/uD/AL5orn9t5Hf/AGJijgW1PUbYgTqSBV6y1uKUASZU+9ac9vDLGRJGpJHXFc7qOjukhMAOM5Nc12fKHSQzRzKGSRWH1p5bb2Oeox2rndJsZ3bbEJiwOAFQkE10p8N67HbCdoLgIADllxkYzmmmdWDpc1VaFq21OTyDFlsAYwTVOeCOQ5B5OScfnVYRTxqScZB5z19KR/tWAQu4Hqc4zRuenm2MbqKNPTl6od9mT0k/Wio913/zxH50U+U4/wC0K/8AMy3zRTzTTUHnGl4Z1688P3ongtILiMHO2TPP5Gu/1P4vXmo6Utr/AGZbwjBBxnIGfXNeXjtSelCNqdVwd0T387XV3JOxAL9QOlV26Zbkegpw4GKaaozk2/efVlfcn90/nRU2B6Ciqub2P//Z'],
                                   ['team_left', 'game_1_H1', '2994', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABfADoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDlKKj3nOKXOBk9K+fujlA9aN6g7d4yBmhmAGetXLbwtc6nbfaLCUCUj7pIyePQ02zWnSlVdolYSK3SnblFVp7e6sLhre4U70OGOOKcp3Hk+9Ts9QrUXTdpFjzewGPxp3nH0qsVHHFLge/50jCUURlsHp0pd24HjFBUHkigADoKS3LZHM4jQsTgCtbwh4oitL4IwO3IG4DtWRc48shgCPQ1qeFrawLJdXCxsuTujzjj61pFXR9DkFKjUqfvD0+LQPC/jK3aSw1AW18QCFcHrj0rz/xX4Y1Dw3qBtrwDH8LLyCPXNTG806HVIpdClljnjJLEghSB16+2e1elNq2keIvDqw6vA8lwqYDkYOfwq3KLj5n0GcZFHk9pDZnihpat6zZGyvXiG4xgnaSOoqluH9/9Kx5kfA1qLjLlkJSZpTTaRJFOHeM47+lUre5utOl3RIpULwGBNdX4cSxMrG8YFcAIScYqh4vhilvSdOQFAMAqOv6mri73R6+UTVOspNmZb6jKLkXSqFxnIUYJBzmvRfCl676cZrg7WLZCgdBiuK8HadbX9+sF/I8TAggbePpzXr9x4Qki0YXVkwKlcAcdaz5Jtn6bmePpPBqCavY898a6hFdXYjiVQEGCQMZrmsrVm/SdLuSKfPmKSDkVX2NRsfkOJquVRsUnANImD1OPSk3qeQcimg59Kq2hh1JAzKw2jkHoK96+CPgvSdb0IXV7EspLEEEHp6enQfrXgg3D5u5716p8EvE+p6cGtxKxhJBIz39a0oyjCXvbG+HpzlNKL1PQfFvwz0qwv11SzsUMIOXGOhFdxY6Fp7+GTbpFEUKZAUAn65ryn4m/ETUre1EFtKVDg5AIOcfWn/Dz4oXD6c1lNAnmkEKWJI/HHSvRWKopbHdevz8jlc80+JmmLp/ii4iDKQTkAd65Sut+J0ep3OvtezxvIrA4YDGOfauP2v715c2pSujkq4epGVmjixf6hbNscscHvV218QIFHmp+RrduLO3kU7olOfWuX1jTGhZnjUiMemTiqTVjk2OktL6C5AKSDJ7cV2XgbUxZzhWKqD1LE/4149ZR3u4SQBhg5GBXS6PqF4ZlWZWjOcZIGKiUUellTviYq+jPQfGs/wBoMZWRcjIypzmuc0/ULiwnWaB9hBBI7HFQyzr5IZ5N3HOTjFVhcQE7TKpJxxmlyr5Ho51h/qmIvB7nWXXjS7vIFiuY0kOBzg5HFYhkjJJ45+tZwli3Z3g59D1rq7a2sTbxkyrkoM9fT61VkaYfO6cIKNSmmznWwB0phRXUoQCG4IIp5BAAPWl4zmpPmjEfTJrd2ltJcAHIQjIArs/A3gvxB4lnUQae/ljku+Ap/E4FZllcPaXC3CIjbCDtYZDexFeoeHfjLfabYpaJotmVAwCrsOPpVRV3qa0pqElLazMHxX8LtZ0iye4uLSEx7ckCUEjjp15/CvOTYW4Y5jXjuOteneMPiZrXiWIQTRQwoBwqZP6k1wTYBJIzVSatZG+Mxk8TJOT1RnS6fEwJVSvGAQelXYmkSJEy3yqB1FPOc5Xj0pv4CoRxa9z/2Q=='],
                                   ['team_left', 'game_1_H1', '2998', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABTADcDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDnT0ppbnml5YU0qetfPI4khQRkClZgvU00ZDCklUnDCiw+W7sMN1GHwXUE9iacGUnggg96nj0+3uwCVXOOT0xTptPNvjA+QdKZ1rA1ZQ54q6K+3nrkUU8AdKKVzk5WtAT5fenFh6VEWyPSmg+tOw7ExxikIyMU0H0z9KHYAE5xQnrYFfdE2lXkcF15cvRzgGu0fSorzT90C5kIyDkYrybW7goSUYhsYBBqx4e17UEGz7Q4AOBkk1pZWPrMoruNNxktDor23kt52jcYIPIoqrNcvK+5nYsevoaKwPnsbb2zsRjijIJ61EXOetJk+tanKTqRkc/lSkK42sSAT1quCQepqxZQtdXMcCsAznAJOBn8qTKjdO5n6lZRyMMgEkgA+laGl+GJ3fagDHGQIwSD+ma7/wAN+BPtl3HHeuwjBy7KcYGPU16fF4M0fTNANzaGVWBK5L5Bx9RXbSwspRue9lWOpUU/aK58/wAulXdsMvC3HXIP0ord+I1+Y9TNpATjAJ4A9+1Fc1SnyyscmKxNCpVclE4sLg5J/Slz/nFYU02rQOCQHA9jRb606uBcoVOfoKg8pM3CcDNLHIUcOhIZTkH0qrDfW8w/dyKSex4qYEfWgpNJWOl8OeL9TsdSiMtyot2cCTIPA6dBXs0fj3Rn8PC18wSqASSpOSSPTHFfOM7fumQICTj3xzU2lX1xaIVRiFJyVIyDXVTxjguVHp0sIuRTbsmbPi++XUtYkuVj8tWOACeeKKyp7x55N0ij8FxRXLOo5O52LLcNNX9oizLDG4AZF+uKyb/SYJ8koAe1b5UE9Ka0anqKz5kfNcyOJudGnhbdCWJHQDils5b6IbZkYDPXdgfrXZvAp5AzTLbbaziUxK+P7wz+nShSuXe+zKWj2d/qWRBYzSdOAuf1q3c6PqNpG7yWUygDJLIeK7LSviLe6ZZ/Z7fTbTIAAYxJj8QBn9aoa9451fVYmR0tYg4wdkIGR9anW5308c4UvZtXOFW7QPhxk+lFWXhBckkknr0FFPU5Lo2f4qcAM0UVHQ5hSBjpTJFXb0oopxGinOBtprAbDx6UUVRREaKKKso//9k=']],
                                  shape=(693, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '1900dd42-4798-4f2f-a717-9a76bd6be88f',
              'x': {'bdata': ('SQwIO1MOmbyUkXk9d7Ezv2l027/bJZ' ... '3nvxljYj/fx5C/LxIZPxssbb/SSdY+'),
                    'dtype': 'f4'},
              'y': {'bdata': ('3rnIQBiqyUC1P5tAFcGfQHQqk0D4Rs' ... 'enQA2fgEAvTpBA+NCGQE8Dl0Cr+nBA'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_1_H1', '78', '201',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA7ABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDkyxdwc5yelRySoriMyANnGM0o+WQBfrTLWx0xrqXVtRnYW8RCGJWILMc4/lXhQi5bIwhSu9x5PJwcilB4pDjeQAQo+7nrTgKiSsyWrERJJyeBwM/U4rO8W28Fp4mbTLOVpYovLJJPVyASCPXNaKSKksTMMqrhiPUAgn+VUfiF/ofjq7vAMRyPHcx8cEFQf6V24B3k0+xsr8ly8xZXYHPBxg+vQ0m6pLu4t764a+tlCwzneoHYkc/rmosCuSppJmMnqCgFcHAJ4yTWT45v5tRt7eW4RYmgjFsuP41XOD+taE4fyHEeCxBAB9cVzmnabe61q9npUd0rM7eUXkOEiPU81vhVyNyubQ1Vkbnh9VTRreJSSFB5PuavUgsLjTUFpNGQImKBxyr4OMg+lNDEjNYVPek2iKkXCVmhSGGQDj1qa3gtF0pUiRYZYWLbl6yk8kn6YqNvvGlQdKiE2tC6dRwehI93cz2sdrJMZI4iSuQMjPUZqseDgVZUDnioyo9KGzOpKU3dn//Z'],
                                   ['team_right', 'game_1_H1', '78', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyACADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDIY4Rs9wRXefHgE2fhJpBgnTBz7YH+NcE/KNyOBmu7+P7qumeEJS2VbTF4PQcCvDopuVl2OGzdkjzAAAEA5A71HIOQavW2oaWmkXdvcBftrlDDjkkd6z2PXJ5pSi4t3Ru4cquapw52k8Hgmtz9onxFcPa6Tpi2rIILKFYWI7BQSQffP6VgAEAkDIAJrofj7e2SeO/DlnqaKmnTaFEXkC8hyCAT6nIFa4R2qX7IdJXZ5j4Rs31nV5GeUKbW3e4OT1C9APrWwclieOeazvA4srbxC8TTt5bpJGzY5K84HpWm4CuwBOATg+1a4uSclYueiL8s8UBHmOoJ4Azz+VVPHfiNPGPiSy1G5hVIra2S0tww4cR8Z6nvnrity/Ph2eBpW064EwIKMHGAAehrqPiP4K8HWmqeHrcieyTUbZWZ1I2REgc5PPU5PFZUZKLduxlF8p5npUumb9Rt1tt05UeXKBwrA5PNSbgQFABAHU1t3vh6y8H6pe6PfI91sYNHNGRh0PIOfpVUXGi7vltJT/wP/wCtWc2m9CpSuDfdr0T9oLiPwtj/AKBy/wAhRRRS3foZHmuoyyzzB5pHkby15diT096pL96iioRXQ//Z'],
                                   ['team_right', 'game_1_H1', '82', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABNACADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD56BxTZZFUAdDUTyYBrF1O8kSbCjiuCMbuyOWKbNpX5J60pckY6Cs6wleSPLHNWtxPek1Z2FJNNojkl5IOMVn38SmQK/BwCM96uF1Rg7LuUEEr6is/WtUk1K+VgioigKAoAwK7MPFWbZcY2VzQsgogGOtTc1BZACBQBjjmpGODgGuacbttES3uVb5isYI59axWBWcbeATmtycB4yrLkeo7VnTbF+XHzA9fatqU1axpCV1Y0LQnyRUpJzmorU5iFSHrWcrpmcnqNJrNvkHn5B5xWgcEfewelZlx5stydm4heu0ZwKdNW1HHQ0LYERBT2qYVGY5Ico5JYDkHqDTs0paES1YtsEEyGUZUEE/TNbmh2+niC78l18533KWGAB6Vg980q5A4JFOLsHNc0tUv4rqApJbqLnOC6jA/+vWYKU/N1pKUmmwP/9k='],
                                   ...,
                                   ['team_right', 'game_1_H1', '2994', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABQADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwChtNLuHrRuHrTa+XPNsx27kAcUnm7cFiAPUmm4GOVx6nNU54TcSACTC9OvWtYQe6NIQc3ZFwXMJYKJFY+gIp4kGPlFR2WgWigyM+G65IBqSSGOFiFcEfSk6bvsdM8K6a1dw3D1opmRRRZnJcWjtntTPmpl0zRoQTgihRvsWozfQo6jdGJSDkfQ1h3WpxRKTHIxPXgVleJp9SCboZBj34rlINVcjbIwPPJOa9/D0Y8uxsmou6O1k8Y3NuAvlvIB3HatPSdbfUCSysjDggmuK02T7WzBAueDgnNdp4f0SZ0DqeD3BxWeIVOnc3U5VFZnRW7sYgc/rRSx2UiKFI6e9FeV7RGHsRxLAcg1VuXf5sjP1NajTwmHAj+b0rMvFLqSBjPSsoaSuy7pLRnJeIj8gXqM1ykthb54Q5z2rr9btbmQfLCxwc8DNYDWV8ZiBAQPUmvosPOMI6sXKN0S3ignUgMCeCT3r07wxdKsRULyBmvPrYvayBpoiQPauw8Oazab1Xy9oPBJIrkxyU7tG1G17I6iR1Lk4H5UVMBZuNwmXB96K8ez7G1kYxIHX9Ks2SW7y4uGXZ6nisae+OMxYArD1K61BQxWcIO2AP8ACq5X2PNg7Su9j1C7uPDcIP8AosIwOz//AF64HXNa01NQAiVAoPQAn+Qrhp727dtrTy59M5oVXIyQ59yD/hXXDSNmzqq11UVrWOrnvdJu2AUMAep6Gus8HWvht1PmR7mOMHPSvNLa5jgc+bCcEYBArTg1CNl3RvtOMgciolKVrJjoVlC10eo3VroomIRo0X0z/wDXorzyJLyZBIssjZ6nIoqLM6HiIdjsNF0STUpRHbwM2f8APrWhq3wx1KZMLwfYrXS/DDxNoHh+OQ6nbyvK2MMoJAwfb613M/xL8Jt0glP0jI/rWMZs8m581Xfg6TS70LdRFT6Fgf5VaTTYPLC+WCR6ium8U36avqz3QUBD0AyKy9gIA4pyqXC5mTaTbSIQ0aj3AFUpfDls54k2jsBXQhFpQoHNP2hXNYoafpwtbYQxzSBQTgYFFaFFT7QXMf/Z'],
                                   ['team_right', 'game_1_H1', '2994', '206',

In [76]:
model_name = "osnet"
method = 'kmeans'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=False, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left        4690         150           0
team_right         90        4883           0
goalkeeper          4         160         180

In [77]:
model_name = "osnet"
method = 'hdbscan'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=True, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left        4674         147           0
team_right        107        4835           0
goalkeeper          0          96         179

In [78]:
print(np.unique(y_true, return_counts=True))
print(np.unique(clusters, return_counts=True))

(array([0, 1, 2]), array([4840, 4973,  344]))
(array([0, 1, 2, 3, 4]), array([ 179,   31, 5078, 4781,   88]))

In [79]:
model_name = "osnet"
method = 'gmm'
X, y_true = embeddings[model_name]
_, clusters = run_clustering(X, y_true, method, is_umap=True, is_pca=False, is_scale=False)
plot_confusion_matrix_clustering(y_true, clusters)

            team_left  team_right  goalkeeper
team_left        4690         150           0
team_right         90        4883           0
goalkeeper          4         160         180

### Подбор гиперпараметов

In [27]:
import optuna
import numpy as np

def objective_umap(trial, X, y, method="kmeans"):

    n_components = trial.suggest_int("n_components", 2, 20)
    n_neighbors = trial.suggest_int("n_neighbors", 5, 100)
    min_dist = trial.suggest_float("min_dist", 0.0, 0.8)
    metric = trial.suggest_categorical("metric", ["cosine", "euclidean"])

    seeds = [0, 1, 2]
    scores = []

    for seed in seeds:

        reducer = umap.UMAP(
            n_components=n_components,
            n_neighbors=n_neighbors,
            min_dist=min_dist,
            metric=metric,
            random_state=seed
        )

        X_umap = reducer.fit_transform(l2norm(X))

        results, _ = run_clustering(
            X_umap,
            y,
            method=method,
            is_umap=False
        )

        score = results["macro_f1_cluster"]

        if not np.isnan(score):
            scores.append(score)

    if len(scores) == 0:
        return -1.0

    return float(np.mean(scores))

def print_callback(study, trial):

    print(
        f"trial {trial.number} finished | "
        f"score={trial.value:.4f} | "
        f"best={study.best_value:.4f}"
    )

In [28]:
study = optuna.create_study(direction="maximize")

study.optimize(
    lambda trial: objective_umap(trial, X, y, method="kmeans"),
    n_trials=60,
    show_progress_bar=True,
    callbacks=[print_callback]
)
print("best score:", study.best_value)
print("best params:", study.best_params)

[I 2026-03-11 01:52:44,912] A new study created in memory with name: no-name-a3918482-46a9-426b-b546-1d31963a087a

  0%|          | 0/60 [00:00<?, ?it/s]

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 01:53:55,906] Trial 0 finished with value: 0.6046166402003917 and parameters: {'n_components': 10, 'n_neighbors': 48, 'min_dist': 0.26620802307552893, 'metric': 'euclidean'}. Best is trial 0 with value: 0.6046166402003917.
trial 0 finished | score=0.6046 | best=0.6046

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 01:55:25,939] Trial 1 finished with value: 0.6349553603168959 and parameters: {'n_components': 18, 'n_neighbors': 68, 'min_dist': 0.03921633707868333, 'metric': 'euclidean'}. Best is trial 1 with value: 0.6349553603168959.
trial 1 finished | score=0.6350 | best=0.6350

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 01:57:21,162] Trial 2 finished with value: 0.6957350006190447 and parameters: {'n_components': 12, 'n_neighbors': 44, 'min_dist': 0.034345120272922094, 'metric': 'cosine'}. Best is trial 2 with value: 0.6957350006190447.
trial 2 finished | score=0.6957 | best=0.6957

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 01:58:22,706] Trial 3 finished with value: 0.7459196094474305 and parameters: {'n_components': 13, 'n_neighbors': 40, 'min_dist': 0.6139312041229934, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 3 finished | score=0.7459 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:00:41,397] Trial 4 finished with value: 0.6470870088569097 and parameters: {'n_components': 5, 'n_neighbors': 98, 'min_dist': 0.6230924640850065, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 4 finished | score=0.6471 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:02:29,135] Trial 5 finished with value: 0.6045205413171866 and parameters: {'n_components': 14, 'n_neighbors': 74, 'min_dist': 0.08157590725935507, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 5 finished | score=0.6045 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:04:56,078] Trial 6 finished with value: 0.6051178499750235 and parameters: {'n_components': 15, 'n_neighbors': 69, 'min_dist': 0.10749295828363117, 'metric': 'cosine'}. Best is trial 3 with value: 0.7459196094474305.
trial 6 finished | score=0.6051 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:05:59,745] Trial 7 finished with value: 0.6625492165742165 and parameters: {'n_components': 8, 'n_neighbors': 23, 'min_dist': 0.647788037661736, 'metric': 'cosine'}. Best is trial 3 with value: 0.7459196094474305.
trial 7 finished | score=0.6625 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:07:06,371] Trial 8 finished with value: 0.6053782642357636 and parameters: {'n_components': 9, 'n_neighbors': 23, 'min_dist': 0.3719493846173966, 'metric': 'cosine'}. Best is trial 3 with value: 0.7459196094474305.
trial 8 finished | score=0.6054 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:08:35,116] Trial 9 finished with value: 0.6506928366346408 and parameters: {'n_components': 3, 'n_neighbors': 40, 'min_dist': 0.287793099616244, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 9 finished | score=0.6507 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:09:24,064] Trial 10 finished with value: 0.7149139278492113 and parameters: {'n_components': 20, 'n_neighbors': 9, 'min_dist': 0.780472385906159, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 10 finished | score=0.7149 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:10:14,469] Trial 11 finished with value: 0.623378536580237 and parameters: {'n_components': 20, 'n_neighbors': 6, 'min_dist': 0.7886349880372223, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 11 finished | score=0.6234 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:11:13,947] Trial 12 finished with value: 0.613338297163359 and parameters: {'n_components': 17, 'n_neighbors': 9, 'min_dist': 0.5880145728198594, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 12 finished | score=0.6133 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:12:50,082] Trial 13 finished with value: 0.7296790057923045 and parameters: {'n_components': 13, 'n_neighbors': 26, 'min_dist': 0.7941912985760874, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 13 finished | score=0.7297 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:14:20,062] Trial 14 finished with value: 0.6041544916918022 and parameters: {'n_components': 13, 'n_neighbors': 31, 'min_dist': 0.5192531235683088, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 14 finished | score=0.6042 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:16:20,303] Trial 15 finished with value: 0.601552334951637 and parameters: {'n_components': 7, 'n_neighbors': 59, 'min_dist': 0.7113727750990434, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 15 finished | score=0.6016 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:17:42,796] Trial 16 finished with value: 0.695511719296323 and parameters: {'n_components': 16, 'n_neighbors': 35, 'min_dist': 0.4767682399906016, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 16 finished | score=0.6955 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:18:44,756] Trial 17 finished with value: 0.6063186409055551 and parameters: {'n_components': 11, 'n_neighbors': 22, 'min_dist': 0.7015519842161202, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 17 finished | score=0.6063 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:21:56,997] Trial 18 finished with value: 0.6262350272607354 and parameters: {'n_components': 13, 'n_neighbors': 58, 'min_dist': 0.5376847353245597, 'metric': 'cosine'}. Best is trial 3 with value: 0.7459196094474305.
trial 18 finished | score=0.6262 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:24:32,289] Trial 19 finished with value: 0.6973469422155761 and parameters: {'n_components': 6, 'n_neighbors': 87, 'min_dist': 0.43378126943733825, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 19 finished | score=0.6973 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:25:35,512] Trial 20 finished with value: 0.6057782447610411 and parameters: {'n_components': 11, 'n_neighbors': 32, 'min_dist': 0.7104615687278716, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 20 finished | score=0.6058 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:26:24,086] Trial 21 finished with value: 0.6060071836292397 and parameters: {'n_components': 20, 'n_neighbors': 17, 'min_dist': 0.7916606483989314, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 21 finished | score=0.6060 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:27:00,834] Trial 22 finished with value: 0.6555923405824555 and parameters: {'n_components': 18, 'n_neighbors': 14, 'min_dist': 0.7897135974889425, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 22 finished | score=0.6556 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:27:51,267] Trial 23 finished with value: 0.6357878127514172 and parameters: {'n_components': 16, 'n_neighbors': 29, 'min_dist': 0.6821405142229926, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 23 finished | score=0.6358 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:28:12,701] Trial 24 finished with value: 0.6426162451296533 and parameters: {'n_components': 14, 'n_neighbors': 5, 'min_dist': 0.5822546379102436, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 24 finished | score=0.6426 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:28:51,813] Trial 25 finished with value: 0.6658477573349378 and parameters: {'n_components': 18, 'n_neighbors': 16, 'min_dist': 0.7407506554824573, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 25 finished | score=0.6658 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:29:29,268] Trial 26 finished with value: 0.6441004283886037 and parameters: {'n_components': 4, 'n_neighbors': 52, 'min_dist': 0.6454959094079171, 'metric': 'cosine'}. Best is trial 3 with value: 0.7459196094474305.
trial 26 finished | score=0.6441 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:29:51,923] Trial 27 finished with value: 0.6904968994691357 and parameters: {'n_components': 2, 'n_neighbors': 36, 'min_dist': 0.7609013214508361, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 27 finished | score=0.6905 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:30:12,168] Trial 28 finished with value: 0.6870164795208177 and parameters: {'n_components': 9, 'n_neighbors': 24, 'min_dist': 0.5516835835493871, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 28 finished | score=0.6870 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:30:40,491] Trial 29 finished with value: 0.6018231498346039 and parameters: {'n_components': 10, 'n_neighbors': 49, 'min_dist': 0.37531011349492965, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 29 finished | score=0.6018 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:31:08,412] Trial 30 finished with value: 0.6349858957779664 and parameters: {'n_components': 19, 'n_neighbors': 42, 'min_dist': 0.17750911331543678, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 30 finished | score=0.6350 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:31:53,224] Trial 31 finished with value: 0.6349738316719363 and parameters: {'n_components': 6, 'n_neighbors': 97, 'min_dist': 0.42658116275596514, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 31 finished | score=0.6350 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:32:35,646] Trial 32 finished with value: 0.6350884965685023 and parameters: {'n_components': 7, 'n_neighbors': 87, 'min_dist': 0.3009937347813758, 'metric': 'euclidean'}. Best is trial 3 with value: 0.7459196094474305.
trial 32 finished | score=0.6351 | best=0.7459

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:33:16,390] Trial 33 finished with value: 0.7548119788517086 and parameters: {'n_components': 12, 'n_neighbors': 83, 'min_dist': 0.42632588765351775, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 33 finished | score=0.7548 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:33:56,013] Trial 34 finished with value: 0.6325360620840562 and parameters: {'n_components': 12, 'n_neighbors': 80, 'min_dist': 0.4892956480082859, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 34 finished | score=0.6325 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:34:28,324] Trial 35 finished with value: 0.6640195019629497 and parameters: {'n_components': 12, 'n_neighbors': 58, 'min_dist': 0.2300826899782076, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 35 finished | score=0.6640 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:35:09,346] Trial 36 finished with value: 0.6663456137570055 and parameters: {'n_components': 15, 'n_neighbors': 63, 'min_dist': 0.613633363963342, 'metric': 'cosine'}. Best is trial 33 with value: 0.7548119788517086.
trial 36 finished | score=0.6663 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:35:38,265] Trial 37 finished with value: 0.6497854880723778 and parameters: {'n_components': 14, 'n_neighbors': 46, 'min_dist': 0.7503408868944701, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 37 finished | score=0.6498 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:35:51,358] Trial 38 finished with value: 0.6208849150009635 and parameters: {'n_components': 10, 'n_neighbors': 10, 'min_dist': 0.6501734334692036, 'metric': 'cosine'}. Best is trial 33 with value: 0.7548119788517086.
trial 38 finished | score=0.6209 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:36:12,863] Trial 39 finished with value: 0.6605870682255719 and parameters: {'n_components': 13, 'n_neighbors': 27, 'min_dist': 0.34265883383126744, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 39 finished | score=0.6606 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:36:37,910] Trial 40 finished with value: 0.6053743097953302 and parameters: {'n_components': 16, 'n_neighbors': 38, 'min_dist': 0.6759818425884754, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 40 finished | score=0.6054 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:37:20,469] Trial 41 finished with value: 0.6274021649158033 and parameters: {'n_components': 5, 'n_neighbors': 92, 'min_dist': 0.44570449039503396, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 41 finished | score=0.6274 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:37:59,905] Trial 42 finished with value: 0.6002307388627502 and parameters: {'n_components': 8, 'n_neighbors': 82, 'min_dist': 0.4241926357182365, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 42 finished | score=0.6002 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:38:38,046] Trial 43 finished with value: 0.6365675193309089 and parameters: {'n_components': 11, 'n_neighbors': 76, 'min_dist': 0.5739090139197556, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 43 finished | score=0.6366 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:39:19,424] Trial 44 finished with value: 0.6124806723247912 and parameters: {'n_components': 9, 'n_neighbors': 90, 'min_dist': 0.49213456016814405, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 44 finished | score=0.6125 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:40:07,339] Trial 45 finished with value: 0.7215726037954707 and parameters: {'n_components': 15, 'n_neighbors': 96, 'min_dist': 0.36101123141276414, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 45 finished | score=0.7216 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:41:05,291] Trial 46 finished with value: 0.6348418323165231 and parameters: {'n_components': 15, 'n_neighbors': 99, 'min_dist': 0.23053601074454283, 'metric': 'cosine'}. Best is trial 33 with value: 0.7548119788517086.
trial 46 finished | score=0.6348 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:41:50,013] Trial 47 finished with value: 0.6958232610680192 and parameters: {'n_components': 17, 'n_neighbors': 95, 'min_dist': 0.33019480648968175, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 47 finished | score=0.6958 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:42:26,124] Trial 48 finished with value: 0.6858766645358562 and parameters: {'n_components': 13, 'n_neighbors': 68, 'min_dist': 0.7439188945178147, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 48 finished | score=0.6859 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:43:04,891] Trial 49 finished with value: 0.6047221659899976 and parameters: {'n_components': 14, 'n_neighbors': 73, 'min_dist': 0.1384231957636654, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 49 finished | score=0.6047 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:43:28,524] Trial 50 finished with value: 0.7269945099056369 and parameters: {'n_components': 12, 'n_neighbors': 34, 'min_dist': 0.6119840495207185, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 50 finished | score=0.7270 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:43:55,891] Trial 51 finished with value: 0.6644312560253808 and parameters: {'n_components': 12, 'n_neighbors': 45, 'min_dist': 0.5224472306115722, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 51 finished | score=0.6644 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:44:13,604] Trial 52 finished with value: 0.6069193592682263 and parameters: {'n_components': 12, 'n_neighbors': 19, 'min_dist': 0.37140860611882603, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 52 finished | score=0.6069 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:44:38,891] Trial 53 finished with value: 0.7067561926668123 and parameters: {'n_components': 15, 'n_neighbors': 33, 'min_dist': 0.6161267232885372, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 53 finished | score=0.7068 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:44:59,590] Trial 54 finished with value: 0.6633847898435689 and parameters: {'n_components': 11, 'n_neighbors': 27, 'min_dist': 0.7195518712470804, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 54 finished | score=0.6634 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:45:14,238] Trial 55 finished with value: 0.6340057344418376 and parameters: {'n_components': 13, 'n_neighbors': 12, 'min_dist': 0.028775527654575472, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 55 finished | score=0.6340 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:45:33,224] Trial 56 finished with value: 0.6480232649289107 and parameters: {'n_components': 14, 'n_neighbors': 20, 'min_dist': 0.4669016801303714, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 56 finished | score=0.6480 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:46:01,446] Trial 57 finished with value: 0.6079766254899531 and parameters: {'n_components': 17, 'n_neighbors': 40, 'min_dist': 0.772132640097133, 'metric': 'cosine'}. Best is trial 33 with value: 0.7548119788517086.
trial 57 finished | score=0.6080 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:46:33,485] Trial 58 finished with value: 0.6040953105089198 and parameters: {'n_components': 19, 'n_neighbors': 53, 'min_dist': 0.672814502966224, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 58 finished | score=0.6041 | best=0.7548

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 02:46:56,691] Trial 59 finished with value: 0.7005640811265786 and parameters: {'n_components': 10, 'n_neighbors': 35, 'min_dist': 0.799694831511757, 'metric': 'euclidean'}. Best is trial 33 with value: 0.7548119788517086.
trial 59 finished | score=0.7006 | best=0.7548
best score: 0.7548119788517086
best params: {'n_components': 12, 'n_neighbors': 83, 'min_dist': 0.42632588765351775, 'metric': 'euclidean'}

In [13]:
import numpy as np
import optuna
from sklearn.decomposition import PCA
import umap

def l2norm(X, eps=1e-12):
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    return X / np.clip(norms, eps, None)


def objective_pca_n_components(trial, X, y, method="kmeans"):
    X_norm = l2norm(X)

    max_comp = min(50, X_norm.shape[1], X_norm.shape[0])
    n_components_pca = trial.suggest_int("pca_n_components", 2, max_comp)

    X_pca = PCA(n_components=n_components_pca).fit_transform(X_norm)

    seeds = [0, 1, 2]
    scores = []

    for seed in seeds:
        reducer = umap.UMAP(
            n_components=10,
            n_neighbors=30,
            min_dist=0.0,
            metric="cosine",
            random_state=seed
        )

        X_umap = reducer.fit_transform(X_pca)

        results, _ = run_clustering(
            X_umap,
            y,
            method=method,
            is_umap=False,
            is_pca=False,
            is_scale=False
        )

        score = results["macro_f1_cluster"]

        if not np.isnan(score):
            scores.append(score)

    if len(scores) == 0:
        return -1.0

    return float(np.mean(scores))

In [17]:
X, y = embeddings["osnet"]
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42)
)

study.optimize(
    lambda trial: objective_pca_n_components(trial, X, y, method="kmeans"),
    n_trials=40,
    show_progress_bar=True
)

print("best score:", study.best_value)
print("best params:", study.best_params)

[I 2026-03-11 08:19:26,809] A new study created in memory with name: no-name-60e7338f-302b-4b4b-93db-3b93092dcb5f

  0%|          | 0/40 [00:00<?, ?it/s]

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:20:15,900] Trial 0 finished with value: 0.7232119366373125 and parameters: {'pca_n_components': 20}. Best is trial 0 with value: 0.7232119366373125.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:21:01,819] Trial 1 finished with value: 0.6611132283216158 and parameters: {'pca_n_components': 48}. Best is trial 0 with value: 0.7232119366373125.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:21:44,100] Trial 2 finished with value: 0.5697148286604765 and parameters: {'pca_n_components': 37}. Best is trial 0 with value: 0.7232119366373125.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:22:26,189] Trial 3 finished with value: 0.8483594274375698 and parameters: {'pca_n_components': 31}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:23:07,778] Trial 4 finished with value: 0.6786146262825583 and parameters: {'pca_n_components': 9}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:23:52,500] Trial 5 finished with value: 0.6786146262825583 and parameters: {'pca_n_components': 9}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:24:32,678] Trial 6 finished with value: 0.5901656065503517 and parameters: {'pca_n_components': 4}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:25:17,035] Trial 7 finished with value: 0.673761406190578 and parameters: {'pca_n_components': 44}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:26:01,095] Trial 8 finished with value: 0.8483594274375698 and parameters: {'pca_n_components': 31}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:26:44,700] Trial 9 finished with value: 0.6816956881461165 and parameters: {'pca_n_components': 36}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:27:31,180] Trial 10 finished with value: 0.6997137550451525 and parameters: {'pca_n_components': 22}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:28:20,078] Trial 11 finished with value: 0.6329522168447439 and parameters: {'pca_n_components': 30}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:29:05,867] Trial 12 finished with value: 0.5896931368779659 and parameters: {'pca_n_components': 28}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:29:48,901] Trial 13 finished with value: 0.6816956881461165 and parameters: {'pca_n_components': 36}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:30:30,956] Trial 14 finished with value: 0.6900560424201189 and parameters: {'pca_n_components': 18}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:31:16,945] Trial 15 finished with value: 0.8483594274375698 and parameters: {'pca_n_components': 31}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:32:04,056] Trial 16 finished with value: 0.7153138937434278 and parameters: {'pca_n_components': 41}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:32:47,198] Trial 17 finished with value: 0.7385147268112737 and parameters: {'pca_n_components': 24}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:33:29,845] Trial 18 finished with value: 0.6355339175215399 and parameters: {'pca_n_components': 32}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:34:12,712] Trial 19 finished with value: 0.7419331094707536 and parameters: {'pca_n_components': 16}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:34:56,928] Trial 20 finished with value: 0.6803276179180914 and parameters: {'pca_n_components': 49}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:35:43,782] Trial 21 finished with value: 0.6355339175215399 and parameters: {'pca_n_components': 32}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:36:30,049] Trial 22 finished with value: 0.7579192405572265 and parameters: {'pca_n_components': 27}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:37:15,982] Trial 23 finished with value: 0.6717140140588941 and parameters: {'pca_n_components': 42}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:38:00,282] Trial 24 finished with value: 0.6447962066370818 and parameters: {'pca_n_components': 33}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:38:45,760] Trial 25 finished with value: 0.7385147268112737 and parameters: {'pca_n_components': 24}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:39:32,016] Trial 26 finished with value: 0.6566939653136107 and parameters: {'pca_n_components': 40}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:40:16,460] Trial 27 finished with value: 0.6353074861714276 and parameters: {'pca_n_components': 29}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:41:00,771] Trial 28 finished with value: 0.797473033324598 and parameters: {'pca_n_components': 15}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:41:45,305] Trial 29 finished with value: 0.7232119366373125 and parameters: {'pca_n_components': 20}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:42:29,527] Trial 30 finished with value: 0.7346119922741564 and parameters: {'pca_n_components': 25}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:43:13,472] Trial 31 finished with value: 0.7331710507242392 and parameters: {'pca_n_components': 14}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:43:59,127] Trial 32 finished with value: 0.6444814701700404 and parameters: {'pca_n_components': 34}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:44:45,394] Trial 33 finished with value: 0.6170837564420222 and parameters: {'pca_n_components': 38}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:45:30,916] Trial 34 finished with value: 0.6358697556146439 and parameters: {'pca_n_components': 45}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:46:13,706] Trial 35 finished with value: 0.7331710507242392 and parameters: {'pca_n_components': 14}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:46:51,983] Trial 36 finished with value: 0.5992764535134582 and parameters: {'pca_n_components': 3}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:47:35,161] Trial 37 finished with value: 0.6786146262825583 and parameters: {'pca_n_components': 9}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:48:21,784] Trial 38 finished with value: 0.6329522168447439 and parameters: {'pca_n_components': 30}. Best is trial 3 with value: 0.8483594274375698.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 08:49:07,006] Trial 39 finished with value: 0.6709407670036184 and parameters: {'pca_n_components': 21}. Best is trial 3 with value: 0.8483594274375698.
best score: 0.8483594274375698
best params: {'pca_n_components': 31}

In [16]:
import numpy as np
import optuna
import umap
import hdbscan

from sklearn.decomposition import PCA
from metrics import macro_f1_clustering


def objective_hdbscan_pca31(trial, X, y):
    # 1) Нормировка
    X_norm = l2norm(X)

    # 2) PCA фиксирован
    X_pca = PCA(n_components=31).fit_transform(X_norm)

    # 3) Подбираем параметры HDBSCAN
    min_cluster_size = trial.suggest_int("min_cluster_size", 5, 50)

    min_samples_mode = trial.suggest_categorical(
        "min_samples_mode", ["none", "value"]
    )
    if min_samples_mode == "none":
        min_samples = None
    else:
        min_samples = trial.suggest_int("min_samples", 1, 25)

    cluster_selection_method = trial.suggest_categorical(
        "cluster_selection_method", ["eom", "leaf"]
    )

    cluster_selection_epsilon = trial.suggest_float(
        "cluster_selection_epsilon", 0.0, 0.2
    )

    # 4) Усреднение по нескольким seed UMAP
    seeds = [0, 1, 2]
    scores = []

    for seed in seeds:
        reducer = umap.UMAP(
            n_components=10,
            n_neighbors=30,
            min_dist=0.0,
            metric="cosine",
            random_state=seed,
        )
        X_umap = reducer.fit_transform(X_pca)

        clusterer = hdbscan.HDBSCAN(
            min_cluster_size=min_cluster_size,
            min_samples=min_samples,
            metric="euclidean",
            cluster_selection_method=cluster_selection_method,
            cluster_selection_epsilon=cluster_selection_epsilon,
            prediction_data=True,
        )

        clusters = clusterer.fit_predict(X_umap)

        noise_fraction = float(np.mean(clusters == -1))
        mask = clusters != -1

        # если все ушло в шум или остался 1 кластер — trial плохой
        if mask.sum() == 0 or len(np.unique(clusters[mask])) < 2:
            scores.append(-1.0)
            continue

        y_clean = np.asarray(y)[mask]
        clusters_clean = clusters[mask]

        macro_f1 = macro_f1_clustering(y_clean, clusters_clean)
        coverage = 1.0 - noise_fraction

        # честная цель: качество * покрытие
        objective_value = macro_f1 * coverage
        scores.append(objective_value)

    return float(np.mean(scores))

In [21]:

def l2norm(X, eps=1e-12):
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    return X / np.clip(norms, eps, None)

X, y = embeddings["osnet"]

sampler = optuna.samplers.TPESampler(seed=42)

study = optuna.create_study(
    direction="maximize",
    sampler=sampler
)

study.optimize(
    lambda trial: objective_hdbscan_pca31(trial, X, y),
    n_trials=80,
    show_progress_bar=True
)

print("best score:", study.best_value)
print("best params:", study.best_params)

[I 2026-03-11 09:05:06,456] A new study created in memory with name: no-name-91ba13ac-840f-4792-aff4-c86dc90dbfec

  0%|          | 0/80 [00:00<?, ?it/s]

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:05:34,032] Trial 0 finished with value: 0.04203967365899582 and parameters: {'min_cluster_size': 22, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.031198904067240532}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:05:55,477] Trial 1 finished with value: 0.02324911850580968 and parameters: {'min_cluster_size': 7, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.19398197043239887}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:06:17,244] Trial 2 finished with value: 0.016326554054590662 and parameters: {'min_cluster_size': 43, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.10495128632644757}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:06:38,662] Trial 3 finished with value: 0.005201035153442207 and parameters: {'min_cluster_size': 24, 'min_samples_mode': 'value', 'min_samples': 4, 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.0912139968434072}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:07:00,098] Trial 4 finished with value: 0.012315392651525902 and parameters: {'min_cluster_size': 41, 'min_samples_mode': 'value', 'min_samples': 15, 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.03410482473745831}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:07:21,687] Trial 5 finished with value: 0.027551542028842708 and parameters: {'min_cluster_size': 7, 'min_samples_mode': 'value', 'min_samples': 21, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1368466053024314}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:07:43,143] Trial 6 finished with value: 0.020562668812164068 and parameters: {'min_cluster_size': 25, 'min_samples_mode': 'value', 'min_samples': 1, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1325044568707964}. Best is trial 0 with value: 0.04203967365899582.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:08:04,565] Trial 7 finished with value: 0.07506970405055179 and parameters: {'min_cluster_size': 19, 'min_samples_mode': 'value', 'min_samples': 5, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.18789978831283782}. Best is trial 7 with value: 0.07506970405055179.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:08:25,998] Trial 8 finished with value: 0.19134319679171855 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'value', 'min_samples': 3, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06506606615265287}. Best is trial 8 with value: 0.19134319679171855.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:08:47,509] Trial 9 finished with value: 0.003926306956581589 and parameters: {'min_cluster_size': 22, 'min_samples_mode': 'value', 'min_samples': 9, 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.02818484499495253}. Best is trial 8 with value: 0.19134319679171855.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:09:09,335] Trial 10 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06937017828132439}. Best is trial 10 with value: 0.5714729363442556.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:09:31,243] Trial 11 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06949231331083612}. Best is trial 10 with value: 0.5714729363442556.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:09:53,521] Trial 12 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07121824466699878}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:10:15,276] Trial 13 finished with value: 0.32189208692689514 and parameters: {'min_cluster_size': 36, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06365725002496159}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:10:36,957] Trial 14 finished with value: 0.32189208692689514 and parameters: {'min_cluster_size': 36, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.003327968641085449}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:10:58,838] Trial 15 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10356217930450393}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:11:20,427] Trial 16 finished with value: 0.19973775927366885 and parameters: {'min_cluster_size': 33, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1347728297881004}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:11:42,021] Trial 17 finished with value: 0.1748360603532516 and parameters: {'min_cluster_size': 31, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.08338492166550011}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:12:03,727] Trial 18 finished with value: 0.013978006190950914 and parameters: {'min_cluster_size': 41, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.044794745180937026}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:12:25,350] Trial 19 finished with value: 0.5306872623200795 and parameters: {'min_cluster_size': 45, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.001621254893564697}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:12:46,935] Trial 20 finished with value: 0.018275949650235913 and parameters: {'min_cluster_size': 13, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.11769746256068578}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:13:08,682] Trial 21 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06888550526048007}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:13:30,376] Trial 22 finished with value: 0.5512520539367146 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.05165404535856359}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:13:52,133] Trial 23 finished with value: 0.5304383763204031 and parameters: {'min_cluster_size': 38, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.08365528043921142}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:14:13,939] Trial 24 finished with value: 0.5513126335669395 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0711844389735542}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:14:35,721] Trial 25 finished with value: 0.5308865920515551 and parameters: {'min_cluster_size': 41, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.049909813409258985}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:14:57,513] Trial 26 finished with value: 0.018879528411162343 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.11546521182253817}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:15:19,276] Trial 27 finished with value: 0.1748360603532516 and parameters: {'min_cluster_size': 31, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.159295737788421}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:15:41,189] Trial 28 finished with value: 0.5306872623200795 and parameters: {'min_cluster_size': 45, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.08396850268358362}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:16:03,099] Trial 29 finished with value: 0.551297489065765 and parameters: {'min_cluster_size': 47, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.018034810589485584}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:16:24,834] Trial 30 finished with value: 0.5304052131935625 and parameters: {'min_cluster_size': 39, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.040272724184576586}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:16:46,577] Trial 31 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0695405401848963}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:17:08,321] Trial 32 finished with value: 0.5307536490659986 and parameters: {'min_cluster_size': 43, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.060032191001362284}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:17:30,144] Trial 33 finished with value: 0.5512520539367146 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07647087446666127}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:17:52,050] Trial 34 finished with value: 0.5307536490659986 and parameters: {'min_cluster_size': 43, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.05554402268905212}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:18:13,950] Trial 35 finished with value: 0.018879528411162343 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.09455980782310071}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:18:35,642] Trial 36 finished with value: 0.5307241301038218 and parameters: {'min_cluster_size': 44, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.026991518055401648}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:18:57,402] Trial 37 finished with value: 0.017712324369528375 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.09530359576444475}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:19:18,977] Trial 38 finished with value: 0.28350790447606816 and parameters: {'min_cluster_size': 40, 'min_samples_mode': 'value', 'min_samples': 24, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.11029085955500567}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:19:40,392] Trial 39 finished with value: 0.029369229128468236 and parameters: {'min_cluster_size': 17, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.03888223640946625}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:20:01,769] Trial 40 finished with value: 0.20311908447242 and parameters: {'min_cluster_size': 43, 'min_samples_mode': 'value', 'min_samples': 16, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07791467947462412}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:20:23,835] Trial 41 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10467252688764825}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:20:45,750] Trial 42 finished with value: 0.551297489065765 and parameters: {'min_cluster_size': 47, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10005811627545627}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:21:07,658] Trial 43 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.09009478242287149}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:21:29,279] Trial 44 finished with value: 0.5512520539367146 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.12187656001901423}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:21:50,474] Trial 45 finished with value: 0.011481292495480848 and parameters: {'min_cluster_size': 5, 'min_samples_mode': 'value', 'min_samples': 10, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.14622644478494023}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:22:11,845] Trial 46 finished with value: 0.008477871870749444 and parameters: {'min_cluster_size': 27, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.06428446410109827}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:22:33,263] Trial 47 finished with value: 0.5304606430962013 and parameters: {'min_cluster_size': 37, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07103791445636204}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:22:54,638] Trial 48 finished with value: 0.2381590874071798 and parameters: {'min_cluster_size': 45, 'min_samples_mode': 'value', 'min_samples': 19, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0887508556815248}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:23:16,396] Trial 49 finished with value: 0.5308090404405381 and parameters: {'min_cluster_size': 42, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1266026793267026}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:23:38,259] Trial 50 finished with value: 0.018280232352681322 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.05780829323775812}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:23:59,839] Trial 51 finished with value: 0.5714729363442556 and parameters: {'min_cluster_size': 50, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07263431485370209}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:24:21,475] Trial 52 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.06787495276284143}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:24:43,054] Trial 53 finished with value: 0.5512520539367146 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.04546685305501236}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:25:04,682] Trial 54 finished with value: 0.5513126335669395 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.08279477565205107}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:25:26,136] Trial 55 finished with value: 0.20329311270115588 and parameters: {'min_cluster_size': 34, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0624571761572319}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:25:47,615] Trial 56 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10127405830481229}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:26:09,071] Trial 57 finished with value: 0.5307241301038218 and parameters: {'min_cluster_size': 44, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.049798122088274235}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:26:30,329] Trial 58 finished with value: 0.017244204647480887 and parameters: {'min_cluster_size': 12, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.027693585088868176}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:26:51,892] Trial 59 finished with value: 0.3308615279515133 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'value', 'min_samples': 25, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1116708471367435}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:27:14,023] Trial 60 finished with value: 0.551297489065765 and parameters: {'min_cluster_size': 47, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0788511454896988}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:27:35,799] Trial 61 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10245923451384377}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:27:57,792] Trial 62 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10050676413461611}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:28:19,622] Trial 63 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10751179813092379}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:28:41,435] Trial 64 finished with value: 0.5306872623200795 and parameters: {'min_cluster_size': 45, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10764521806318204}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:29:03,430] Trial 65 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.09936064828961799}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:29:25,230] Trial 66 finished with value: 0.551297489065765 and parameters: {'min_cluster_size': 47, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1427539848945736}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:29:46,954] Trial 67 finished with value: 0.04203967365899582 and parameters: {'min_cluster_size': 22, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.1261553035309026}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:30:08,724] Trial 68 finished with value: 0.5308090404405381 and parameters: {'min_cluster_size': 42, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.11732437608944385}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:30:30,622] Trial 69 finished with value: 0.01840081758509552 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'leaf', 'cluster_selection_epsilon': 0.089145915996697}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:30:52,477] Trial 70 finished with value: 0.5513126335669395 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.09860336660136947}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:31:14,570] Trial 71 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10075978100391288}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:31:36,318] Trial 72 finished with value: 0.5307241301038218 and parameters: {'min_cluster_size': 44, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.19688689199482867}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:31:58,365] Trial 73 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.11303508986443633}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:32:20,219] Trial 74 finished with value: 0.551297489065765 and parameters: {'min_cluster_size': 47, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.09457626702583252}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:32:42,029] Trial 75 finished with value: 0.571516688849048 and parameters: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.17614879191775082}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:33:03,557] Trial 76 finished with value: 0.5306872623200795 and parameters: {'min_cluster_size': 45, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.08313792646567048}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:33:25,483] Trial 77 finished with value: 0.3225251679714416 and parameters: {'min_cluster_size': 40, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10759392287675268}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:33:48,913] Trial 78 finished with value: 0.5512520539367146 and parameters: {'min_cluster_size': 48, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.12245234736543487}. Best is trial 12 with value: 0.571516688849048.

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[I 2026-03-11 09:34:11,078] Trial 79 finished with value: 0.1975399389601609 and parameters: {'min_cluster_size': 46, 'min_samples_mode': 'value', 'min_samples': 11, 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.10359749075226926}. Best is trial 12 with value: 0.571516688849048.
best score: 0.571516688849048
best params: {'min_cluster_size': 49, 'min_samples_mode': 'none', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.07121824466699878}